### ISSUE TITLE
--try-toolchain hard crash when no easyconfig is specified

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#1154]
```
$ eb --software=R,3.1.2 --toolchain=intel,2015a -D --amend=versionsuffix=-bare --try-toolchain=intel,2014b   
Couldn't import dot_parser, loading of dot files will not be possible.
== temporary log file in case of crash /var/folders/8s/_frgh9sj6m744mxt5w5lyztr0000gn/T/easybuild-MdA9dz/easybuild-Y7Q6pq.log
Traceback (most recent call last):
  File "/Users/kehoste/work/easybuild-framework/easybuild/main.py", line 335, in <module>
    main()
  File "/Users/kehoste/work/easybuild-framework/easybuild/main.py", line 186, in main
    (try_to_generate, build_specs) = process_software_build_specs(options)
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/options.py", line 685, in process_software_build_specs
    self.log.warning("Ignoring --try-%(opt)s, only using --%(opt)s specification" % {'opt': opt})
NameError: global name 'self' is not defined
```

**Comment by Micket** [comment]
This doesn't happen anymore from what I can tell with an updated version string of software and versions.
