### ISSUE TITLE
Issues with install 2.7 when older vsc-install is present

### ISSUE THREAD

**Issue by wpoely86** [easybuilders/easybuild-framework#1684]
Debug log: https://gist.github.com/31484c3cf4e65d3e3edb

``` python
Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    shared_setup.action_target(PACKAGE)
  File "external_dist_only/shared_setup_dist_only.py", line 1335, in action_target
    setupfn(**x)
  File "/usr/lib64/python2.6/distutils/core.py", line 113, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 221, in __init__
    self.fetch_build_eggs(attrs.pop('setup_requires'))
  File "/usr/lib/python2.6/site-packages/setuptools/dist.py", line 245, in fetch_build_eggs
    parse_requirements(requires), installer=self.fetch_build_egg
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 550, in resolve
    raise VersionConflict(dist,req) # XXX put more info here
pkg_resources.VersionConflict: (vsc-install 0.9.15 (/usr/lib/python2.6/site-packages), Requirement.parse('vsc-install>=0.9.19'))
 (at easybuild/tools/run.py:397 in parse_cmd_output)
```

**Comment by wpoely86** [comment]
No longer relevant
