### ISSUE TITLE
cyclic dependency not handled well

### ISSUE THREAD

**Issue by shahzebsiddiqui** [easybuilders/easybuild-framework#2184]
https://github.com/hpcugent/easybuild-easyconfigs/issues/4408

**Comment by shahzebsiddiqui** [comment]
I am still getting an error after removing GCC from its dependency. I am running a dry-run and it is failing.
```
    return modules_tool_class(mod_paths=mod_paths, testing=testing)
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/modules.py", line 998, in __init__
    setvar('LMOD_QUIET', '1', verbose=False)
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/environment.py", line 97, in setvar
    _log.info("Environment variable %s set to %s (%s)", key, value, oldval_info)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1149, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1268, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1278, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1318, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib64/python2.7/logging/handlers.py", line 82, in emit
    self.handleError(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib64/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib64/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib64/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib64/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib64/python2.7/linecache.py", line 128, in updatecache
    lines = fp.readlines()
RuntimeError: maximum recursion depth exceeded while calling a Python object
```
```
[hpcswadm@amrndhl1157 intelcuda]$ cat intelcuda-2017.01.eb 
easyblock = 'Toolchain'

name = 'intelcuda'
version = '2017.01'

homepage = '(none)'
description = """Intel Cluster Toolkit Compiler Edition provides Intel C/C++ and Fortran compilers,
 Intel MPI & Intel MKL, with CUDA toolkit"""

toolchain = {'name': 'dummy', 'version': 'dummy'}

comp_name = 'iccifort'
comp_ver = '2017.1.132'
gccver = '5.4.0'
binutilsver = '2.27'
gccsuff = '-GCC-%s-%s' % (gccver, binutilsver)
comp = (comp_name, '%s%s' % (comp_ver, gccsuff))

dependencies = [
    ('icc', comp_ver, gccsuff),
    ('ifort', comp_ver, gccsuff),
    ('CUDA', '8.0.44', '', comp),
    ('impi', comp_ver, '', ('iccifortcuda', version)),
    ('imkl', comp_ver, '', ('iimpic', version)),
]

moduleclass = 'toolchain'
```

**Comment by boegel** [comment]
@shahzebsiddiqui The traceback you are showing is quite strange... It's getting stuck in an infinite loop while defining a simple environment variable?!

What happens if you run this?

```
python -c "from easybuild.tools.environment import setvar; setvar('LMOD_QUIET', '1', verbose=False); import os; print os.getenv('LMOD_QUIET')"
```

**Comment by shahzebsiddiqui** [comment]
```
[hpcswadm@amrndhl1157 easybuild]$ python -c "from easybuild.tools.environment import setvar; setvar('LMOD_QUIET', '1', verbose=False); import os; print os.getenv('LMOD_QUIET')"
1
```

**Comment by boegel** [comment]
@shahzebsiddiqui Can you provide a full debug log for this?

**Comment by shahzebsiddiqui** [comment]
I ran the command using 

[hpcswadm@amrndhl1157 intelcuda]$ eb intelcuda-2017.01.eb -d --robot --devel

Please see the log
[easybuild-qQw9z2.txt](https://github.com/hpcugent/easybuild-framework/files/882540/easybuild-qQw9z2.txt)

Snapshot of error
```
    return os.path.join(self.det_module_subdir(ec), self.det_short_module_name(ec))
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/module_naming_scheme/hierarchical_mns.py", line 129, in det_module_subdir
    tc_comps = det_toolchain_compilers(ec)
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/module_naming_scheme/toolchain.py", line 93, in det_toolchain_compilers
    tc_elems = ec.toolchain.definition()
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 659, in toolchain
    tc_ec = process_easyconfig(tc_ecfile)[0]
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 1260, in process_easyconfig
    ec = EasyConfig(spec, build_specs=build_specs, validate=validate, hidden=hidden)
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 278, in __init__
    self.modules_tool = modules_tool()
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/modules.py", line 1240, in modules_tool
    return modules_tool_class(mod_paths=mod_paths, testing=testing)
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/modules.py", line 998, in __init__
    setvar('LMOD_QUIET', '1', verbose=False)
  File "/nfs/grid/software/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/tools/environment.py", line 97, in setvar
    _log.info("Environment variable %s set to %s (%s)", key, value, oldval_info)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1149, in info
    self._log(INFO, msg, args, **kwargs)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1268, in _log
    self.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1278, in handle
    self.callHandlers(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 1318, in callHandlers
    hdlr.handle(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 749, in handle
    self.emit(record)
  File "/usr/lib64/python2.7/logging/handlers.py", line 82, in emit
    self.handleError(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib64/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib64/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib64/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib64/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib64/python2.7/linecache.py", line 128, in updatecache
    lines = fp.readlines()
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by shahzebsiddiqui** [comment]
Is IntelCuda going to be fixed for EB 3.2 release?

**Comment by boegel** [comment]
@shahzebsiddiqui This is a very strange problem, I'm not sure it's a bug in EasyBuild at all, it looks like a problem with Python itself.

The problem occurs when EasyBuild is doing something very simply, i.e. defining the environment variable `$LMOD_QUIET` to `1`. The log message being emitted when doing that somehow triggers and infinite loop in your Python installation, I have no idea why that happens...

On what kind of system are you running into this? Which OS, which Python version, which filesystem, etc.?

One thing you can consider is to try and bump the recursion limit a bit, by adding this to the top of `easybuild/main.py`:

```python
import sys
print 'recursion limit: ', sys.getrecursionlimit()
sys.setrecursionlimit(1500)
```

**Comment by shahzebsiddiqui** [comment]
Hi Ken

Please see the system information below.
```
[hpcswadm@amrndhl1157 3.1.2]$ python -V
Python 2.7.5
[hpcswadm@amrndhl1157 3.1.2]$ which python
/bin/python
[hpcswadm@amrndhl1157 3.1.2]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 7.2 (Maipo)
[hpcswadm@amrndhl1157 3.1.2]$ uname -r
3.10.0-327.36.1.el7.x86_64
[hpcswadm@amrndhl1157 3.1.2]$ lscpu
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                80
On-line CPU(s) list:   0-79
Thread(s) per core:    2
Core(s) per socket:    10
Socket(s):             4
NUMA node(s):          4
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 62
Model name:            Intel(R) Xeon(R) CPU E7-8891 v2 @ 3.20GHz
Stepping:              7
CPU MHz:               3200.000
BogoMIPS:              6430.37
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              38400K
NUMA node0 CPU(s):     0-9,40-49
NUMA node1 CPU(s):     10-19,50-59
NUMA node2 CPU(s):     20-29,60-69
NUMA node3 CPU(s):     30-39,70-79

```

We are running NFS v3 for installing apps and few other services. We use AFS for home directories. The file that you are asking to edit is it.

```
[hpcswadm@amrndhl1157 3.1.2]$ pwd
/nfs/grid/testing/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2
[hpcswadm@amrndhl1157 3.1.2]$ find . -name main.py
./lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/main.py
```

Content of main is as follows
```
158 def main(args=None, logfile=None, do_build=None, testing=False, modtool=None):
159     """
160     Main function: parse command line options, and act accordingly.
161     :param args: command line arguments to use
162     :param logfile: log file to use
163     :param do_build: whether or not to actually perform the build
164     :param testing: enable testing mode
165     """
166     # purposely session state very early, to avoid modules loaded by EasyBuild meddling in
167     init_session_state = session_state()
168 
169     # initialise options
170     eb_go = eboptions.parse_options(args=args)
171     options = eb_go.options
172     orig_paths = eb_go.args

```

**Comment by shahzebsiddiqui** [comment]
The issue doesn't seem to be a system python issue something to do with the eb files. I tried with Python and Anaconda from eb and this error only happens on intelcuda dependency tree. It also happens building iccifortcuda. 

I can't build any intelcuda related packages.

```
hpcswadm@amrndhl1157 easybuild]$ ml OpenMPI
[hpcswadm@amrndhl1157 easybuild]$ ml Python
[hpcswadm@amrndhl1157 easybuild]$ ml

Currently Loaded Modules:
  1) EasyBuild/3.1.2   6) hwloc/1.11.3                                  11) bzip2/.1.0.6      16) SQLite/.3.13.0
  2) GCCcore/.5.4.0    7) OpenMPI/2.0.0                                 12) zlib/.1.2.8       17) Tk/.8.6.5
  3) binutils/.2.27    8) OpenBLAS/0.2.19-LAPACK-3.6.0                  13) ncurses/.6.0      18) GMP/6.1.1
  4) GCC/5.4.0-2.27    9) FFTW/3.3.4                                    14) libreadline/.6.3  19) libffi/.3.2.1
  5) numactl/2.0.11   10) ScaLAPACK/2.0.2-OpenBLAS-0.2.19-LAPACK-3.6.0  15) Tcl/.8.6.5        20) Python/2.7.12

[hpcswadm@amrndhl1157 easybuild]$ python -V
Python 2.7.12
[hpcswadm@amrndhl1157 intelcuda]$ eb intelcuda-2017.01.eb -D
== temporary log file in case of crash /dev/shm/tmp/eb-svghpc/easybuild-yeDfgU.log
Traceback (most recent call last):
  File "/nfs/grid/testing/RHEL7/easybuild/software/MPI/GCC/5.4.0-2.27/OpenMPI/2.0.0/Python/2.7.12/lib/python2.7/logging/handlers.py", line 78, in emit
Traceback (most recent call last):
  File "/nfs/grid/testing/RHEL7/easybuild/software/MPI/GCC/5.4.0-2.27/OpenMPI/2.0.0/Python/2.7.12/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/nfs/grid/testing/RHEL7/easybuild/software/MPI/GCC/5.4.0-2.27/OpenMPI/2.0.0/Python/2.7.12/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/nfs/grid/testing/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/main.py", line 453, in <module>
    main()
  File "/nfs/grid/testing/RHEL7-BUILD/easybuild/software/EasyBuild/3.1.2/lib/python2.7/site-packages/easybuild_framework-3.1.2-py2.7.egg/easybuild/main.py", line 338, in main
```

```
[hpcswadm@amrndhl1157 intelcuda]$ ml GCC/5.4.0-2.27 
[hpcswadm@amrndhl1157 intelcuda]$ ml Anaconda2
[hpcswadm@amrndhl1157 intelcuda]$ ml

Currently Loaded Modules:
  1) GCCcore/.5.4.0   2) binutils/.2.27   3) GCC/5.4.0-2.27   4) Anaconda2/4.2.0

[hpcswadm@amrndhl1157 intelcuda]$ python -V
Python 2.7.12 :: Anaconda 4.2.0 (64-bit)

  File "/nfs/grid/testing/RHEL7/easybuild/software/Compiler/GCC/5.4.0-2.27/Anaconda2/4.2.0/lib/python2.7/logging/__init__.py", line 759, in handle
    self.emit(record)
  File "/nfs/grid/testing/RHEL7/easybuild/software/Compiler/GCC/5.4.0-2.27/Anaconda2/4.2.0/lib/python2.7/logging/handlers.py", line 82, in emit
    self.handleError(record)
  File "/nfs/grid/testing/RHEL7/easybuild/software/Compiler/GCC/5.4.0-2.27/Anaconda2/4.2.0/lib/python2.7/logging/__init__.py", line 812, in handleError
    None, sys.stderr)
  File "/nfs/grid/testing/RHEL7/easybuild/software/Compiler/GCC/5.4.0-2.27/Anaconda2/4.2.0/lib/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/nfs/grid/testing/RHEL7/easybuild/software/Compiler/GCC/5.4.0-2.27/Anaconda2/4.2.0/lib/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/nfs/grid/testing/RHEL7/easybuild/software/Compiler/GCC/5.4.0-2.27/Anaconda2/4.2.0/lib/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/nfs/grid/testing/RHEL7/easybuild/software/Compiler/GCC/5.4.0-2.27/Anaconda2/4.2.0/lib/python2.7/linecache.py", line 41, in getlines
    return updatecache(filename, module_globals)
  File "/nfs/grid/testing/RHEL7/easybuild/software/Compiler/GCC/5.4.0-2.27/Anaconda2/4.2.0/lib/python2.7/linecache.py", line 132, in updatecache
    lines = fp.readlines()
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

**Comment by boegel** [comment]
@shahzebsiddiqui Can you upload the easyconfig files you are using for `intelcuda-2017.01.eb` somewhere?

Are you also hitting this problem when using the `intelcuda-2016.10.eb` we have included currently in EasyBuild?

**Comment by shahzebsiddiqui** [comment]
It looks like the issue doesn't happen with intelcuda-2016.10.eb I will try to test intelcuda-2017.01.eb again.

**Comment by shahzebsiddiqui** [comment]
I am still getting the issue with intelcuda-2017.01.eb

This is just a snippet of the error
```
-bash-4.2$ eb intelcuda-2017.01.eb -D
== temporary log file in case of crash /dev/shm/tmp/eb-gB2NwL/easybuild-Q2lF0N.log
Traceback (most recent call last):
  File "/usr/lib64/python2.7/logging/handlers.py", line 78, in emit
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/nfs/grid/software/RHEL7/easybuild/software/Core/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg/easybuild/main.py", line 483, in <module>
    main()
  File "/nfs/grid/software/RHEL7/easybuild/software/Core/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg/easybuild/main.py", line 362, in main
    easyconfigs, generated_ecs = parse_easyconfigs(paths)
  File "/nfs/grid/software/RHEL7/easybuild/software/Core/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg/easybuild/framework/easyconfig/tools.py", line 382, in parse_easyconfigs
    ecs = process_easyconfig(ec_file, **kwargs)
  File "/nfs/grid/software/RHEL7/easybuild/software/Core/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 1261, in process_easyconfig
    ec = EasyConfig(spec, build_specs=build_specs, validate=validate, hidden=hidden)
  File "/nfs/grid/software/RHEL7/easybuild/software/Core/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 324, in __init__
    self.parse()
  File "/nfs/grid/software/RHEL7/easybuild/software/Core/EasyBuild/3.3.1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 455, in parse
    self._finalize_dependencies()
```

Here is the end of the error
```
    self.emit(record)
  File "/usr/lib64/python2.7/logging/handlers.py", line 82, in emit
    self.handleError(record)
  File "/usr/lib64/python2.7/logging/__init__.py", line 802, in handleError
    None, sys.stderr)
  File "/usr/lib64/python2.7/traceback.py", line 125, in print_exception
    print_tb(tb, limit, file)
  File "/usr/lib64/python2.7/traceback.py", line 69, in print_tb
    line = linecache.getline(filename, lineno, f.f_globals)
  File "/usr/lib64/python2.7/linecache.py", line 14, in getline
    lines = getlines(filename, module_globals)
  File "/usr/lib64/python2.7/linecache.py", line 40, in getlines
    return updatecache(filename, module_globals)
  File "/usr/lib64/python2.7/linecache.py", line 128, in updatecache
    lines = fp.readlines()
RuntimeError: maximum recursion depth exceeded while calling a Python object

```

My eb configuration is the following

```
-bash-4.2$ eb --show-config
#
# Current EasyBuild configuration
# (C: command line argument, D: default value, E: environment variable, F: configuration file)
#
buildpath            (E) = /dev/shm/easybuild/build
hide-deps            (E) = Autoconf, Automake, Autotools, binutils, Bison, bzip2, cURL, Doxygen, expat, flex, fontconfig, foss, freetype, GCCcore, gcccuda, GDAL, gettext, gompi, gompic, goolfc, icc, iccifort, iccifortcuda, ifort, iimpi, iimpic, inputproto, iompi, kbproto, libffi, libgtextutils, libICE, libjpeg-turbo, libpng, libpthread-stubs, libreadline, libSM, LibTIFF, libtool, libX11, libXau, libxcb, libXdmcp, libXext, libXft, libxml2, libXrender, libXt, M4, motif, NASM, ncurses, NLopt, pkg-config, PROJ, renderproto, SQLite, Szip, Tcl, Tk, util-linux, xbitmaps, xcb-proto, xextproto, xorg-macros, xproto, xtrans, XZ, zlib
hide-toolchains      (E) = GCCcore, iccifort, iimpi, gompi, gcccuda, gompic, foss, goolfc, iompi
installpath          (E) = /nfs/grid/software/RHEL7/easybuild
module-naming-scheme (E) = HierarchicalMNS
package-release      (E) = 2
packagepath          (E) = /dev/shm/easybuild/packages/production
prefix               (E) = /dev/shm/easybuild
repositorypath       (E) = /dev/shm/easybuild/ebfiles_repo
robot-paths          (E) = /home/siddis14/easybuild-easyconfigs/easybuild/easyconfigs
sourcepath           (E) = /dev/shm/easybuild/sources
tmpdir               (E) = /dev/shm/tmp

```

I think you can reproduce the same error if you clone https://github.com/shahzebsiddiqui/easybuild-easyconfigs and try building intelcuda. I am not sure if it has to do with the dependency section. Robot doesn't seem to resolve this correctly.

**Comment by shahzebsiddiqui** [comment]
Not sure if there is something wrong with my easyconfigs. 
```
-bash-4.2$ eb -S intelcuda
CFGS1=/home/siddis14/easybuild-easyconfigs/easybuild/easyconfigs
 * $CFGS1/h/HPL/HPL-2.2-intelcuda-2016.10.eb
 * $CFGS1/i/intelcuda/intelcuda-2016.10.eb
 * $CFGS1/i/intelcuda/intelcuda-2017.01.eb

-bash-4.2$ eb -S iccifortcuda
CFGS1=/home/siddis14/easybuild-easyconfigs/easybuild/easyconfigs/i
 * $CFGS1/iccifortcuda/iccifortcuda-2016.10.eb
 * $CFGS1/iccifortcuda/iccifortcuda-2017.1.132-GCC-5.4.0-2.27.eb
 * $CFGS1/impi/impi-2017.1.132-iccifortcuda-2017.1.132-GCC-5.4.0-2.27.eb
 * $CFGS1/impi/impi-5.1.3.181-iccifortcuda-2016.10.eb

-bash-4.2$ eb -S iimpic
CFGS1=/home/siddis14/easybuild-easyconfigs/easybuild/easyconfigs/i
 * $CFGS1/iimpic/iimpic-2016.10.eb
 * $CFGS1/iimpic/iimpic-2017.01.eb
 * $CFGS1/imkl/imkl-11.3.3.210-iimpic-2016.10.eb
 * $CFGS1/imkl/imkl-2017.1.132-iimpic-2017.01-GCC-5.4.0-2.27.eb
```

**Comment by shahzebsiddiqui** [comment]
@boegel I got intelcuda to work, there was quite a few errors in my easyconfig files that caused the issue. I had named my files incorrectly see https://github.com/shahzebsiddiqui/easybuild-easyconfigs/commit/12613c598584cef0a7b535f89affa57d74f15848 for more details.

I will try to create a PR for this.  There will be a slight change in all the eb files since I use binutils 2.27 with GCC-5.4.0. 
```
-bash-4.2$ eb intelcuda-2017.01.eb -D
== temporary log file in case of crash /dev/shm/tmp/eb-1ffUKf/easybuild-TG70y1.log
Dry run: printing build status of easyconfigs and dependencies
CFGS=/home/siddis14/easybuild-easyconfigs/easybuild/easyconfigs
 * [x] $CFGS/m/M4/M4-1.4.17.eb (module: Core | M4/.1.4.17)
 * [x] $CFGS/b/Bison/Bison-3.0.4.eb (module: Core | Bison/.3.0.4)
 * [x] $CFGS/f/flex/flex-2.6.0.eb (module: Core | flex/.2.6.0)
 * [x] $CFGS/z/zlib/zlib-1.2.8.eb (module: Core | zlib/.1.2.8)
 * [x] $CFGS/b/binutils/binutils-2.27.eb (module: Core | binutils/.2.27)
 * [x] $CFGS/g/GCCcore/GCCcore-5.4.0.eb (module: Core | GCCcore/.5.4.0)
 * [x] $CFGS/m/M4/M4-1.4.17-GCCcore-5.4.0.eb (module: Compiler/GCCcore/5.4.0 | M4/.1.4.17)
 * [x] $CFGS/z/zlib/zlib-1.2.8-GCCcore-5.4.0.eb (module: Compiler/GCCcore/5.4.0 | zlib/.1.2.8)
 * [x] $CFGS/b/Bison/Bison-3.0.4-GCCcore-5.4.0.eb (module: Compiler/GCCcore/5.4.0 | Bison/.3.0.4)
 * [x] $CFGS/f/flex/flex-2.6.0-GCCcore-5.4.0.eb (module: Compiler/GCCcore/5.4.0 | flex/.2.6.0)
 * [x] $CFGS/b/binutils/binutils-2.27-GCCcore-5.4.0.eb (module: Compiler/GCCcore/5.4.0 | binutils/.2.27)
 * [x] $CFGS/i/icc/icc-2017.1.132-GCC-5.4.0-2.27.eb (module: Core | icc/.2017.1.132-GCC-5.4.0-2.27)
 * [x] $CFGS/i/ifort/ifort-2017.1.132-GCC-5.4.0-2.27.eb (module: Core | ifort/.2017.1.132-GCC-5.4.0-2.27)
 * [x] $CFGS/i/iccifort/iccifort-2017.1.132-GCC-5.4.0-2.27.eb (module: Core | iccifort/.2017.1.132-GCC-5.4.0-2.27)
 * [ ] $CFGS/c/CUDA/CUDA-8.0.44-iccifort-2017.1.132-GCC-5.4.0-2.27.eb (module: Compiler/intel/2017.1.132-GCC-5.4.0-2.27 | CUDA/8.0.44)
 * [ ] $CFGS/i/iccifortcuda/iccifortcuda-2017.01.eb (module: Core | iccifortcuda/.2017.01)
 * [ ] $CFGS/i/impi/impi-2017.1.132-iccifortcuda-2017.01.eb (module: Compiler/intel-CUDA/2017.1.132-GCC-5.4.0-2.27-8.0.44 | impi/2017.1.132)
 * [ ] $CFGS/i/iimpic/iimpic-2017.01.eb (module: Core | iimpic/.2017.01)
 * [ ] $CFGS/i/imkl/imkl-2017.1.132-iimpic-2017.01.eb (module: MPI/intel-CUDA/2017.1.132-GCC-5.4.0-2.27-8.0.44/impi/2017.1.132 | imkl/2017.1.132)
 * [ ] $CFGS/i/intelcuda/intelcuda-2017.01.eb (module: Core | intelcuda/2017.01)

```

**Comment by boegel** [comment]
@shahzebsiddiqui Great, thanks for clearing this up.

You basically introduced a cyclic dependency by using the `iccifortcuda` toolchain when installing `CUDA`.

EasyBuild should be handling this more gracefully though...

**Comment by shahzebsiddiqui** [comment]
I am glad this is resolved, at some point I will upload the intelcuda 2017.01 easyconfig files. I got everything installed, but I have to make a few modification. Do you want the files to be intelcuda-2017b.eb

**Comment by boegel** [comment]
follow-up in https://github.com/easybuilders/easybuild-easyconfigs/pull/4993
