### ISSUE TITLE
EasyBuild install > TypeError: __init__() takes exactly 2 arguments (4 given)

### ISSUE THREAD

**Issue by shawarden** [easybuilders/easybuild-framework#2289]
Trying to install via the bootstrap_eb.py it crashes with the above error.

easybuild install process:

```
export EASYBUILD_PREFIX=/resource/easybuild
export EASYBUILD_BOOTSTRAP_DEBUG=1
wget https://raw.githubusercontent.com/easybuilders/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py;
python bootstrap_eb.py $EASYBUILD_PREFIX
```

output:

```
Traceback (most recent call last):
  File "setup.py", line 1520, in <module>
    action_target(PACKAGE)
  File "setup.py", line 1498, in action_target
    _fvs('action_target function')().action_target(package, *args, **kwargs)
  File "setup.py", line 1486, in action_target
    setupfn(**x)
  File "/usr/lib64/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/site-packages/setuptools/command/install.py", line 101, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 380, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 604, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 655, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 701, in process_distribution
    distreq.project_name, distreq.specs, requirement.extras
TypeError: __init__() takes exactly 2 arguments (4 given)
 (at easybuild/tools/run.py:444 in parse_cmd_output)
== 2017-08-25 11:50:28,433 easyblock.py:2577 WARNING build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --prefix /resource/easybuild/software/EasyBuild/3.3.1 vsc-install &&  /usr/bin/python setup.py install --
prefix=/resource/easybuild/software/EasyBuild/3.3.1 " exited with exitcode 1 and output:
Creating /resource/easybuild/software/EasyBuild/3.3.1/lib/py
== 2017-08-25 11:50:28,433 easyblock.py:277 INFO Closing log for application name EasyBuild version 3.3.1
== 2017-08-25 11:50:28,437 easyblock.py:277 INFO Closing log for application name EasyBuild version 3.3.1
== 2017-08-25 11:50:28,437 build_log.py:231 INFO FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpQg_VUz/EasyBuild/3.3.1/dummy-dummy): build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --p$
efix /resource/easybuild/software/EasyBuild/3.3.1 vsc-install &&  /usr/bin/python setup.py install --prefix=/resource/easybuild/software/EasyBuild/3.3.1 " exited with exitcode 1 and output:
Creating /resource/easybuild/software/EasyBuild/3.3.1/lib/py
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpQg_VUz/EasyBuild/3.3.1/dummy-dummy): build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --prefix /resource/easybuild/software/EasyBuild/3.
3.1 vsc-install &&  /usr/bin/python setup.py install --prefix=/resource/easybuild/software/EasyBuild/3.3.1 " exited with exitcode 1 and output:
Creating /resource/easybuild/software/EasyBuild/3.3.1/lib/py
== 2017-08-25 11:50:28,438 build_log.py:231 INFO Results of the build can be found in the log file(s) /tmp/eb-FLdlCM/easybuild-EasyBuild-3.3.1-20170825.115015.szwOl.log
== Results of the build can be found in the log file(s) /tmp/eb-FLdlCM/easybuild-EasyBuild-3.3.1-20170825.115015.szwOl.log
== 2017-08-25 11:50:28,439 build_log.py:156 ERROR EasyBuild crashed with an error (at ?:124 in __init__): build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --prefix /resource/easybuild/software/EasyBuild/3.3.
1 vsc-install &&  /usr/bin/python setup.py install --prefix=/resource/easybuild/software/EasyBuild/3.3.1 " exited with exitcode 1 and output:
Creating /resource/easybuild/software/EasyBuild/3.3.1/lib/py (at easybuild/main.py:121 in build_and_install_software)
== 2017-08-25 11:50:28,440 filetools.py:1095 DEBUG Not creating existing path /tmp/eb-FLdlCM
== 2017-08-25 11:50:28,442 build_log.py:156 ERROR EasyBuild crashed with an error (at ?:124 in __init__): Build of /tmp/tmpQg_VUz/EasyBuild-3.3.1.eb failed (err: 'build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install
) -U --prefix /resource/easybuild/software/EasyBuild/3.3.1 vsc-install &&  /usr/bin/python setup.py install --prefix=/resource/easybuild/software/EasyBuild/3.3.1 " exited with exitcode 1 and output:\nCreating /resource/easybuild/softwar
e/EasyBuild/3.3.1/lib/py') (at easybuild/main.py:153 in build_and_install_software)
Traceback (most recent call last):
  File "bootstrap_eb.py", line 1024, in <module>
    main()
  File "bootstrap_eb.py", line 827, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 697, in stage2
    easybuild_main()
  File "/tmp/tmpQg_VUz/eb_stage1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg/easybuild/main.py", line 452, in main
    ecs_with_res = build_and_install_software(ordered_ecs, init_session_state, exit_on_failure=exit_on_failure)
  File "/tmp/tmpQg_VUz/eb_stage1/lib/python2.7/site-packages/easybuild_framework-3.3.1-py2.7.egg/easybuild/main.py", line 153, in build_and_install_software
    raise EasyBuildError(test_msg)
easybuild.tools.build_log.EasyBuildError: 'Build of /tmp/tmpQg_VUz/EasyBuild-3.3.1.eb failed (err: \'build failed (first 300 chars): cmd "/usr/bin/python $(which easy_install) -U --prefix /resource/easybuild/software/EasyBuild/3.3.1 vsc
-install &&  /usr/bin/python setup.py install --prefix=/resource/easybuild/software/EasyBuild/3.3.1 " exited with exitcode 1 and output:\\nCreating /resource/easybuild/software/EasyBuild/3.3.1/lib/py\')'
```

debug output and log attached

[easybuild.zip](https://github.com/easybuilders/easybuild-framework/files/1250508/easybuild.zip)

**Comment by shawarden** [comment]
Reinstalling python-setuptools.noarch seems to have resolved this.****

**Comment by boegel** [comment]
@shawarden Seems like the setuptools you were using (0.9.8) was buggy?

**Comment by shawarden** [comment]
Probably. The site-packages had screwy permissions when re-installed via pip so I checked the system packages and just reinstalled that.
