### ISSUE TITLE
bootstrap_eb.py fails on Ubuntu 16.04

### ISSUE THREAD

**Issue by adamryczkowski** [easybuilders/easybuild-framework#2354]
Error:

```
[[INFO]] EasyBuild bootstrap script (version 20170808.01, MD5: b970595c701de1ddda0cb8f83448f1f4)
[[INFO]] Found Python 2.7.12 (default, Nov 19 2016, 06:48:10) ; [GCC 5.4.0 20160609]

[[INFO]] Installation prefix /home/adam/.local/easybuild
[[INFO]] Found module command '/usr/share/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
[[INFO]] No suitable setuptools installation found, proceeding with stage 0...


[[INFO]] +++ STAGE 0: installing distribute via included (patched) distribute_setup.py...

Downloading https://easybuilders.github.io/easybuild/files/distribute-0.6.49-patched1.tar.gz
Extracting in /tmp/tmpjRN3ms
Now working in /tmp/tmpjRN3ms/distribute-0.6.49
Installing Distribute
[[INFO]] Installed setuptools version 0.6 (/tmp/tmpu_ZNAz/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/__init__.pyc)


[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpu_ZNAz/eb_stage1 easybuild'
[[ERROR]] Running 'easy_install --quiet --upgrade --prefix=/tmp/tmpu_ZNAz/eb_stage1 easybuild' failed: error: Could not find suitable distribution for Requirement.parse('easybuild')
Traceback (most recent call last):
  File "bootstrap_eb.py", line 339, in run_easy_install
    easy_install.main(args)
  File "/tmp/tmpu_ZNAz/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/command/easy_install.py", line 1973, in main
    with_ei_usage(lambda:
  File "/tmp/tmpu_ZNAz/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/command/easy_install.py", line 1954, in with_ei_usage
    return f()
  File "/tmp/tmpu_ZNAz/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/command/easy_install.py", line 1977, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 166, in setup
    raise SystemExit, "error: " + str(msg)
SystemExit: error: Could not find suitable distribution for Requirement.parse('easybuild')

```

Steps to reproduce:

1. Install Ubuntu 16.04 (tested on LXC container and VirtualBox)
2. Download the bootstrap script `wget https://raw.githubusercontent.com/easybuilders/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py`
3. Install the lmod and python: `sudo apt install lmod python`
4. Execute the lmod profile init script `source /usr/share/lmod/lmod/init/profile`
5. Run the bootstrap script `python bootstrap_eb.py $HOME/.local/easybuild`

**Comment by adamryczkowski** [comment]
Installing setuptools changes the error:

`sudo apt install python-setuptools`

```
python bootstrap_eb.py $HOME/.local/easybuild
[[INFO]] EasyBuild bootstrap script (version 20170808.01, MD5: b970595c701de1ddda0cb8f83448f1f4)
[[INFO]] Found Python 2.7.12 (default, Nov 19 2016, 06:48:10) ; [GCC 5.4.0 20160609]

[[INFO]] Installation prefix /home/adam/.local/easybuild
[[INFO]] Found module command '/usr/share/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
[[INFO]] Suitable setuptools installation already found, skipping stage 0...


[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpfvHBXD/eb_stage1 easybuild'
sh: 1: git: not found
[[ERROR]] Running 'easy_install --quiet --upgrade --prefix=/tmp/tmpfvHBXD/eb_stage1 easybuild' failed: error: Couldn't find a setup script in /tmp/easy_install-Wmk0zG/vsc-base-2.5.8/temp/easy_install-ofws_Z/vsc-install.git
Traceback (most recent call last):
  File "bootstrap_eb.py", line 339, in run_easy_install
    easy_install.main(args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 2293, in main
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib/python2.7/distutils/core.py", line 166, in setup
    raise SystemExit, "error: " + str(msg)
SystemExit: error: Couldn't find a setup script in /tmp/easy_install-Wmk0zG/vsc-base-2.5.8/temp/easy_install-ofws_Z/vsc-install.git

```

**Comment by ocaisa** [comment]
There is no git command available
```
sh: 1: git: not found
```
installing git should get you further. For more details on the real problem see https://github.com/easybuilders/easybuild-framework/issues/1962

**Comment by ocaisa** [comment]
Also, there are some python packages that are requirements (and include `setuptools` and `vsc-install`), these are outlined in http://easybuild.readthedocs.io/en/latest/Installation.html#required-python-packages

**Comment by adamryczkowski** [comment]
Hurray! Installing **git** solved the problem. Beside me, 2 seasoned HPC administrators were trying to troubleshoot this problem for over 1 hour. 

Please, add the git to the list of the compulsory requirements to save time for others. 

Or should I file a separate issue for that?

**Comment by ocaisa** [comment]
#1962 talks through this issue, `git` is not a requirement for EasyBuild. The problem stems from using an old version of setuptools.

**Comment by boegel** [comment]
When no sufficiently recent version of `setuptools` is found, the EasyBuild bootstrap script tries to install one first, but that's known to be troublesome on some systems.

`git` is required because of `vsc-install`, see also https://github.com/hpcugent/vsc-base/issues/243.
It is not required for EasyBuild itself though (unless you want to use the GitHub integration features, cfr. easybuild.readthedocs.io/en/latest/Integration_with_GitHub.html.

@adamryczkowski I feel this issue can be closed since the issues you reported are already known?
