### ISSUE TITLE
Endless loop during initialization with non-existing directories in MODULEPATH

### ISSUE THREAD

**Issue by SethosII** [easybuilders/easybuild-framework#2408]
I recently switched from using `.../modules/all` in the `MODULEPATH` to `.../modules/{bio,compiler,...}` and for completeness sake I added all categories that EasyBuild currently has, but since then EasyBuild gets stuck:

```
# just an example also happens with other options/easyconfigs
$ eb --buildpath=/dev/shm --optarch=march=corei7 --prefix=/mnt/fhgfs_ribdata/easybuild/test SAMt
ools-1.4-foss-2016b.eb --try-software-version=1.3.1 -dr                                                              
== temporary log file in case of crash /tmp/eb-rUJBLU/easybuild-lQ_eaM.log
# log shows endless loop, aborting with Ctrl+C
^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/main.py", line 504, in <module>
    main()
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/main.py", line 377, in main
    easyconfigs, generated_ecs = parse_easyconfigs(paths, validate=not options.inject_checksums)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/tools.py", line 384, in parse_easyconfigs
    ecs = process_easyconfig(ec_file, **kwargs)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 1261, in process_easyconfig
    ec = EasyConfig(spec, build_specs=build_specs, validate=validate, hidden=hidden)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 324, in __init__
    self.parse()
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 455, in parse
    self._finalize_dependencies()
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 906, in _finalize_dependencies
    tc = robot_find_minimal_toolchain_of_dependency(dep, self.modules_tool, parent_first=True)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 1448, in robot_find_minimal_toolchain_of_dependenc
y
    toolchain_hierarchy = get_toolchain_hierarchy(parent_tc)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 128, in cache_aware_func
    toolchain_hierarchy = func(toolchain)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 189, in get_toolchain_hierarchy
    easyconfig = process_easyconfig(ecfile, validate=False)[0]['ec']
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 1303, in process_easyconfig
    tc = ec.toolchain.as_dict()
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 659, in toolchain
    tc_ec = process_easyconfig(tc_ecfile)[0]
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 1261, in process_easyconfig
    ec = EasyConfig(spec, build_specs=build_specs, validate=validate, hidden=hidden)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/framework/easyconfig/easyconfig.py", line 278, in __init__
    self.modules_tool = modules_tool()
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/tools/modules.py", line 1354, in modules_tool
    return modules_tool_class(mod_paths=mod_paths, testing=testing)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/tools/modules.py", line 1118, in __init__
    super(Lmod, self).__init__(*args, **kwargs)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/tools/modules.py", line 197, in __init__
    self.check_module_path()
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/tools/modules.py", line 414, in check_module_path
    self.prepend_module_path(mod_path)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/tools/modules.py", line 1215, in prepend_module_path
    self.use(path)
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/tools/modules.py", line 336, in use
    self.run_module(['use', path])
  File "/mnt/fhgfs_ribdata/easybuild/16.04/software/EasyBuild/3.5.1/lib/python2.7/site-packages/easybuild_framework-3
.5.1-py2.7.egg/easybuild/tools/modules.py", line 669, in run_module
    (stdout, stderr) = proc.communicate()
  File "/usr/lib/python2.7/subprocess.py", line 800, in communicate
    return self._communicate(input)
  File "/usr/lib/python2.7/subprocess.py", line 1417, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python2.7/subprocess.py", line 1471, in _communicate_with_poll
    ready = poller.poll()
KeyboardInterrupt
```

Here is the log: [easybuild-lQ_eaM.log](https://github.com/easybuilders/easybuild-framework/files/1736687/easybuild-lQ_eaM.log).

If I remove all non-existing directories from `MODULEPATH` everything is fine again. So the problem is that EasyBuild can't handle non-existing directories in `MODULEPATH`.

**Comment by boegel** [comment]
@SethosII How much time did you give it? This looks very related to #2226...

Are you using Lmod? If so, which version?

**Comment by SethosII** [comment]
@boegel I tried again and in the end it took more than 10 minutes. So indeed, no endless loop ;) Yes, I'm using `Lmod` version `7.7.14`. So I will close this one and move to the other issue.
