### ISSUE TITLE
--new-pr is broken in EasyBuild 3.5.2

### ISSUE THREAD

**Issue by vanzod** [easybuilders/easybuild-framework#2423]
When using `--new-pr` with `EasyBuild-3.5.2`, it fails since it tries to push to the upstream `easybuilders/easybuild-easyconfigs repo instead of the personal fork.

```
$ eb --new-pr SOAPdenovo2-r240-GCC-5.4.0-2.26.eb
== temporary log file in case of crash /tmp/eb-k5gvAg/easybuild-fpxS9p.log
Please enter password for encrypted keyring: 
== copying /opt/easybuild/EB-develop/easybuild-easyconfigs...
== fetching branch 'develop' from https://github.com/easybuilders/easybuild-easyconfigs.git...
== copying easyconfigs to /tmp/eb-k5gvAg/git-working-dirGKeyPj/easybuild-easyconfigs...
== pushing branch '20180302132539_new_pr_SOAPdenovo2r240' to remote 'github_easybuilders_Fsfyg' (git@github.com:easybuilders/easybuild-easyconfigs.git)
Loading keys:
    /home/davide/.ssh/id_rsa
Enter passphrase for /home/davide/.ssh/id_rsa: 

Opening pull request
* target: easybuilders/easybuild-easyconfigs:develop
* from: vanzod/easybuild-easyconfigs:20180302132539_new_pr_SOAPdenovo2r240
* title: "{bio}[GCC/5.4.0-2.26] SOAPdenovo2 vr240"
* description:
"""
(created using `eb --new-pr`)

"""
* overview of changes:
 .../SOAPdenovo2/SOAPdenovo2-r240-GCC-5.4.0-2.26.eb | 34 ++++++++++++++++++++++
 1 file changed, 34 insertions(+)

Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/opt/easybuild/software/Core/EasyBuild/3.5.2/lib/python2.7/site-packages/easybuild_framework-3.5.2-py2.7.egg/easybuild/main.py", line 504, in <module>
    main()
  File "/opt/easybuild/software/Core/EasyBuild/3.5.2/lib/python2.7/site-packages/easybuild_framework-3.5.2-py2.7.egg/easybuild/main.py", line 421, in main
    commit_msg=options.pr_commit_msg)
  File "/opt/easybuild/software/Core/EasyBuild/3.5.2/lib/python2.7/site-packages/easybuild_framework-3.5.2-py2.7.egg/easybuild/tools/github.py", line 1123, in new_pr
    status, data = pulls_url.post(body=body)
  File "/opt/easybuild/software/Core/EasyBuild/3.5.2/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 144, in post
    return self.request(self.POST, url, json.dumps(body), headers, content_type='application/json')
  File "/opt/easybuild/software/Core/EasyBuild/3.5.2/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 175, in request
    conn = self.get_connection(method, url, body, headers)
  File "/opt/easybuild/software/Core/EasyBuild/3.5.2/lib/python2.7/site-packages/vsc_base-2.5.8-py2.7.egg/vsc/utils/rest.py", line 206, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 422: Unprocessable Entity
```

**Comment by boegel** [comment]
@vanzod Can you verify that #2426 fixes this problem?

**Comment by boegel** [comment]
follow-up in #2426
