### ISSUE TITLE
pypi_source_urls function broken

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#2447]
Probably an upstream issue at PyPI, seems this worked fine before....
Reported at https://github.com/pypa/pypi-legacy/issues/783

```
python -O -m test.framework.suite pypi
INFO: This is (based on) vsc.install.shared_setup 0.10.32
Filtered GeneralTest tests using 'pypi', retained 0/4 tests:
Filtered BuildLogTest tests using 'pypi', retained 0/6 tests:
Filtered CommandLineOptionsTest tests using 'pypi', retained 0/78 tests:
Filtered RepositoryTest tests using 'pypi', retained 0/6 tests:
Filtered EasyConfigFormatTest tests using 'pypi', retained 0/1 tests:
Filtered EasyConfigVersion tests using 'pypi', retained 0/9 tests:
Filtered TestEBConfigObj tests using 'pypi', retained 0/7 tests:
Filtered EasyConfigParserTest tests using 'pypi', retained 0/7 tests:
Filtered EasyConfigTest tests using 'pypi', retained 0/52 tests:
Filtered TclModuleGeneratorTest tests using 'pypi', retained 0/17 tests:
Filtered LuaModuleGeneratorTest tests using 'pypi', retained 0/17 tests:
Filtered ModulesTest tests using 'pypi', retained 0/24 tests:
Filtered ModulesToolTest tests using 'pypi', retained 0/4 tests:
Filtered FileToolsTest tests using 'pypi', retained 3/44 tests: test_derive_alt_pypi_url, test_is_alt_pypi_url, test_pypi_source_urls
Filtered RunTest tests using 'pypi', retained 0/16 tests:
Filtered RobotTest tests using 'pypi', retained 0/12 tests:
Filtered EasyBlockTest tests using 'pypi', retained 0/25 tests:
Filtered VariablesTest tests using 'pypi', retained 0/2 tests:
Filtered GithubTest tests using 'pypi', retained 0/11 tests:
Filtered ToolchainVariablesTest tests using 'pypi', retained 0/1 tests:
Filtered ToolchainTest tests using 'pypi', retained 0/38 tests:
Filtered ToyBuildTest tests using 'pypi', retained 0/38 tests:
Filtered EasyBuildConfigTest tests using 'pypi', retained 0/10 tests:
Filtered SystemToolsTest tests using 'pypi', retained 0/41 tests:
Filtered LicenseTest tests using 'pypi', retained 0/4 tests:
Filtered ConvertTest tests using 'pypi', retained 0/7 tests:
Filtered ScriptsTest tests using 'pypi', retained 0/2 tests:
Filtered TweakTest tests using 'pypi', retained 0/4 tests:
Filtered ParallelBuildTest tests using 'pypi', retained 0/3 tests:
Filtered IncludeTest tests using 'pypi', retained 0/5 tests:
Filtered PackageTest tests using 'pypi', retained 0/4 tests:
Filtered DocsTest tests using 'pypi', retained 0/3 tests:
Filtered EnvironmentTest tests using 'pypi', retained 0/1 tests:
Filtered TypeCheckingTest tests using 'pypi', retained 0/18 tests:
Filtered YebTest tests using 'pypi', retained 0/5 tests:
Filtered StyleTest tests using 'pypi', retained 0/2 tests:
Filtered HooksTest tests using 'pypi', retained 0/4 tests:
WARNING: xmlrunner module not available, falling back to using unittest...

E.E.
======================================================================
ERROR: test_derive_alt_pypi_url (test.framework.filetools.FileToolsTest)
Test derive_alt_pypi_url() function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kehoste/work/easybuild-framework/test/framework/filetools.py", line 1117, in test_derive_alt_pypi_url
    self.assertEqual(ft.derive_alt_pypi_url(url), alturl)
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/filetools.py", line 424, in derive_alt_pypi_url
    cand_urls = pypi_source_urls(pkg_name)
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/filetools.py", line 403, in pypi_source_urls
    parsed_html = ElementTree.parse(urls_html)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 65, column 6

======================================================================
ERROR: test_pypi_source_urls (test.framework.filetools.FileToolsTest)
Test pypi_source_urls() function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/kehoste/work/easybuild-framework/test/framework/filetools.py", line 1100, in test_pypi_source_urls
    res = ft.pypi_source_urls('easybuild')
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/filetools.py", line 403, in pypi_source_urls
    parsed_html = ElementTree.parse(urls_html)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: mismatched tag: line 65, column 6

----------------------------------------------------------------------
Ran 4 tests in 4.467s

FAILED (errors=2)
ERROR: Not all tests were successful.
```

**Comment by boegel** [comment]
Should be fixed now, see https://github.com/pypa/pypi-legacy/issues/783 and https://github.com/pypa/warehouse/pull/3294.
