### ISSUE TITLE
error when using eb --new-pr

### ISSUE THREAD

**Issue by smoors** [easybuilders/easybuild-framework#2495]
when I create a PR with `eb --new-pr`, it works, but then I get this error:
```
== temporary log file in case of crash /tmp/smoors/eb-lwSRJY/easybuild-DTwRYo.log
== fetching branch 'develop' from https://github.com/easybuilders/easybuild-easyconfigs.git...
== copying easyconfigs to /tmp/smoors/eb-lwSRJY/git-working-dira93jO_/easybuild-easyconfigs...
== pushing branch '20180502115945_new_pr_SLEPc383' to remote 'github_smoors_JmkkH' (git@github.com:smoors/easybuild-easyconfigs.git)

Opening pull request
* target: easybuilders/easybuild-easyconfigs:develop
* from: smoors/easybuild-easyconfigs:20180502115945_new_pr_SLEPc383
* title: "{numlib}[foss/2017b] SLEPc v3.8.3"
* labels: update
* description:
"""
(created using `eb --new-pr`)

"""
* overview of changes:
 easybuild/easyconfigs/s/SLEPc/SLEPc-3.8.3-foss-2017b.eb | 21 +++++++++++++++++++++
 1 file changed, 21 insertions(+)

Opened pull request: https://github.com/easybuilders/easybuild-easyconfigs/pull/6260
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/gpfs/work/smoors/hpc/easybuild-dev/easybuild-framework/easybuild/main.py", line 510, in <module>
    main()
  File "/gpfs/work/smoors/hpc/easybuild-dev/easybuild-framework/easybuild/main.py", line 427, in main
    commit_msg=options.pr_commit_msg)
  File "/gpfs/work/smoors/hpc/easybuild-dev/easybuild-framework/easybuild/tools/github.py", line 1151, in new_pr
    status, data = pr_url.labels.post(body=labels)
  File "/work/smoors/hpc/easybuild-dev/vsc-base/lib/vsc/utils/rest.py", line 144, in post
    return self.request(self.POST, url, json.dumps(body), headers, content_type='application/json')
  File "/work/smoors/hpc/easybuild-dev/vsc-base/lib/vsc/utils/rest.py", line 175, in request
    conn = self.get_connection(method, url, body, headers)
  File "/work/smoors/hpc/easybuild-dev/vsc-base/lib/vsc/utils/rest.py", line 206, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

**Comment by boegel** [comment]
fixed in #2497
