### ISSUE TITLE
Easybuild set_up_configuration fails due to setuptools when using Python installed by EB

### ISSUE THREAD

**Issue by victorusu** [easybuilders/easybuild-framework#2742]
I am trying to use the Python3 version of EB and I am using a python 3 version that was installed with EasyBuild.

Since EasyBuild adds the following to the installed python
```
 cat /home/easybuild/Bin/mojave/software/Core/Python-bare/3.7.2/lib/python3.7/site-packages/setuptools.pth
/home/easybuild/Bin/mojave/software/Core/Python-bare/3.7.2/lib/python3.7/site-packages
```

Then I cannot run the `set_up_configuration()` because the `setuptools` overwrite the local dir import. The error I am getting is
```
python3 -c "from easybuild.tools.options import set_up_configuration; set_up_configuration()"
Traceback (most recent call last):
  File "/home/easybuild/Work/Development-Projects/easybuild/easybuild-framework-fork/easybuild/tools/options.py", line 1222, in parse_options
    with_include=with_include)
  File "/home/easybuild/Work/Development-Projects/easybuild/easybuild-framework-fork/easybuild/tools/options.py", line 235, in __init__
    super(EasyBuildOptions, self).__init__(*args, **kwargs)
  File "/home/easybuild/Work/Development-Projects/easybuild/easybuild-framework-fork/easybuild/base/generaloption.py", line 912, in __init__
    self.main_options()
  File "/home/easybuild/Work/Development-Projects/easybuild/easybuild-framework-fork/easybuild/base/generaloption.py", line 988, in main_options
    fn()
  File "/home/easybuild/Work/Development-Projects/easybuild/easybuild-framework-fork/easybuild/tools/options.py", line 487, in config_options
    'choice', 'store', DEFAULT_REPOSITORY, sorted(avail_repositories().keys())),
  File "/home/easybuild/Work/Development-Projects/easybuild/easybuild-framework-fork/easybuild/tools/repository/repository.py", line 152, in avail_repositories
    raise EasyBuildError("avail_repositories: FileRepository missing from list of repositories")
easybuild.tools.build_log.EasyBuildError: 'avail_repositories: FileRepository missing from list of repositories'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/easybuild/Work/Development-Projects/easybuild/easybuild-framework-fork/easybuild/tools/options.py", line 1257, in set_up_configuration
    eb_go = parse_options(args=args)
  File "/home/easybuild/Work/Development-Projects/easybuild/easybuild-framework-fork/easybuild/tools/options.py", line 1224, in parse_options
    raise EasyBuildError("Failed to parse configuration options: %s" % err)
easybuild.tools.build_log.EasyBuildError: "Failed to parse configuration options: 'avail_repositories: FileRepository missing from list of repositories'"
```

The only way I could run the `set_up_configuration()` was by setting 
```
PYTHONPATH=$PWD python3 -c "from easybuild.tools.options import set_up_configuration; set_up_configuration()"
```

**Comment by boegel** [comment]
This issue is caused by `setuptools.pth` magic, see also https://github.com/easybuilders/easybuild-framework/issues/2659#issuecomment-459360719

**Comment by boegel** [comment]
Turns out the problem is actually a bug, fix is in #2786
