### ISSUE TITLE
Warnings during tests

### ISSUE THREAD

**Issue by surak** [easybuilders/easybuild-framework#2771]
Are they expected? How can one have a 'clean' test?

```
WARNING: Failed to determine toolchain hierarchy for GCC/6.4.0-2.28 when determining subtoolchain for dependency 'hwloc': 'Could not find easyconfig for GCC toolchain version 6.4.0-2.28'

.Skipping test_dep_graph, since pygraph is not available
.
WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'first': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'second': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'first': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'second': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'foo': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'bar': 'Could not find easyconfig for GCC toolchain version 4.6.3'

.....Skipping test_dump_autopep8, since autopep8 is not available
./tmp/eb-7eG3Bv/eb-JcnMcd/eb-yxEReVFWTgiE.eb:24:19: W292 no newline at end of file
........
WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'first': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'second': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'first': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'second': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'first': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'second': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'first': 'Could not find easyconfig for GCC toolchain version 4.6.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.6.3 when determining subtoolchain for dependency 'second': 'Could not find easyconfig for GCC toolchain version 4.6.3'

...
WARNING: Failed to determine toolchain hierarchy for gompic/2018a when determining subtoolchain for dependency 'OpenBLAS': 'Could not find easyconfig for gompic toolchain version 2018a'

....
WARNING: Deprecated functionality, will no longer work in v4.0: Named argument 'default_fallback' for get_easyblock_class is deprecated, use 'error_on_missing_easyblock' instead; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

..........
WARNING: Failed to determine toolchain hierarchy for GCC/4.8.3 when determining subtoolchain for dependency 'testbuildonly': 'Could not find easyconfig for GCC toolchain version 4.8.3'


WARNING: Failed to determine toolchain hierarchy for GCC/4.8.3 when determining subtoolchain for dependency 'foo': 'Could not find easyconfig for GCC toolchain version 4.8.3'
```

**Comment by ocaisa** [comment]
Currently yes, afraid so.

**Comment by surak** [comment]
ok, happens. But how to have one that produces no errors?

```
======================================================================
ERROR [2.260s]: test_generate_software_list (test.framework.scripts.ScriptsTest)
Test for generate_software_list.py script.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/test/framework/scripts.py", line 85, in test_generate_software_list
    out, ec = run_cmd(cmd, simple=False)
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/easybuild/tools/run.py", line 87, in cache_aware_func
    res = func(cmd, *args, **kwargs)
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/easybuild/tools/run.py", line 239, in run_cmd
    return parse_cmd_output(cmd, stdouterr, ec, simple, log_all, log_ok, regexp)
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/easybuild/tools/run.py", line 501, in parse_cmd_output
    raise EasyBuildError('cmd "%s" exited with exit code %s and output:\n%s', cmd, ec, stdouterr)
EasyBuildError: 'cmd "/usr/bin/python /software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/easybuild/scripts/generate_software_list.py --local --quiet --path /tmp/eb-7eG3Bv/eb-JcnMcd/eb-eT68aG/eb-6H9adE/tmpNNjYXI" exited with exit code 1 and output:\n== temporary log file in case of crash /tmp/eb-7eG3Bv/eb-JcnMcd/eb-eT68aG/eb-6H9adE/eb-OAgtX0/easybuild-qRK6sx.log\nTraceback (most recent call last):\n  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/easybuild/scripts/generate_software_list.py", line 137, in <module>\n    raise EasyBuildError("faulty easyconfig %s: %s", ec_file, err)\neasybuild.tools.build_log.EasyBuildError: "faulty easyconfig /tmp/eb-7eG3Bv/eb-JcnMcd/eb-eT68aG/eb-6H9adE/tmpNNjYXI/ifort-2016.1.150-GCC-4.9.3-2.25.eb: \'Failed to import EB_ifort easyblock: No module named tbb\'"\n'

======================================================================
FAIL [5.675s]: test_gitrepo (test.framework.repository.RepositoryTest)
Test using GitRepository.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/test/framework/repository.py", line 110, in test_gitrepo
    self.assertTrue(log_regex.search(logmsg), "Pattern '%s' found in %s" % (log_regex.pattern, logmsg))
AssertionError: None is not true : Pattern 'toy/0.0 with EasyBuild v3.8.1 @ .* \(time: .*, user: .*\)' found in commit 8456f867b03aa001fd5a6fe5a0c4300145c065dc
Author: Jens Timmerman <jens.timmerman@ugent.be>
Date:   Wed Oct 24 16:01:05 2012 +0200

    added some more files

======================================================================
FAIL [1.484s]: test_modulerc (test.framework.module_generator.TclModuleGeneratorTest)
Test modulerc method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/test/framework/module_generator.py", line 370, in test_modulerc
    self.assertEqual(len(res), 1)
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/vsc_install-0.11.3-py2.7.egg/vsc/install/testing.py", line 93, in assertEqual
    raise AssertionError("%s:\nDIFF%s:\n%s" % (msg, limit, ''.join(diff[:self.ASSERT_MAX_DIFF])))
AssertionError: 2 != 1:
DIFF:
- 2

======================================================================
FAIL [1.506s]: test_modulerc (test.framework.module_generator.LuaModuleGeneratorTest)
Test modulerc method.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/test/framework/module_generator.py", line 370, in test_modulerc
    self.assertEqual(len(res), 1)
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/vsc_install-0.11.3-py2.7.egg/vsc/install/testing.py", line 93, in assertEqual
    raise AssertionError("%s:\nDIFF%s:\n%s" % (msg, limit, ''.join(diff[:self.ASSERT_MAX_DIFF])))
AssertionError: 2 != 1:
DIFF:
- 2

======================================================================
FAIL [0.557s]: test_find_eb_script (test.framework.filetools.FileToolsTest)
Test find_eb_script function.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/test/framework/filetools.py", line 1548, in test_find_eb_script
    self.assertErrorRegex(EasyBuildError, "Script 'no_such_script' not found", ft.find_eb_script, 'no_such_script')
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/vsc_install-0.11.3-py2.7.egg/vsc/install/testing.py", line 140, in assertErrorRegex
    self.assertTrue(regex.search(msg), "Pattern '%s' is found in '%s'" % (regex.pattern, msg))
AssertionError: None is not true : Pattern 'Script 'no_such_script' not found' is found in 'Resolving path None failed: 'NoneType' object has no attribute 'startswith''

======================================================================
FAIL [0.861s]: test_prepare_step (test.framework.easyblock.EasyBlockTest)
Test prepare step (setting up build environment).
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/test/framework/easyblock.py", line 1374, in test_prepare_step
    self.assertEqual(self.modtool.list(), [])
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/vsc_install-0.11.3-py2.7.egg/vsc/install/testing.py", line 93, in assertEqual
    raise AssertionError("%s:\nDIFF%s:\n%s" % (msg, limit, ''.join(diff[:self.ASSERT_MAX_DIFF])))
AssertionError: Lists differ: [{'default': None, 'mod_name':... != []

First list contains 1 additional elements.
First extra element 0:
{'default': None, 'mod_name': 'EasyBuild/fake'}

- [{'default': None, 'mod_name': 'EasyBuild/fake'}]
+ []:
DIFF:
- [{'default': None, 'mod_name': 'EasyBuild/fake'}]

======================================================================
FAIL [0.641s]: test_modules_tool (test.framework.lib.EasyBuildLibTest)
Test use of modules_tool function in the context of using EasyBuild framework as a library.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/easybuild_framework-3.8.1-py2.7.egg/test/framework/lib.py", line 122, in test_modules_tool
    self.assertEqual(modtool.list(), [{'default': None, 'mod_name': 'GCC/6.4.0-2.28'}])
  File "/software/software/EasyBuild/3.8.1/lib/python2.7/site-packages/vsc_install-0.11.3-py2.7.egg/vsc/install/testing.py", line 93, in assertEqual
    raise AssertionError("%s:\nDIFF%s:\n%s" % (msg, limit, ''.join(diff[:self.ASSERT_MAX_DIFF])))
AssertionError: Lists differ: [{'default': None, 'mod_name':... != [{'default': None, 'mod_name':...

First differing element 0:
{'default': None, 'mod_name': 'EasyBuild/3.8.1'}
{'default': None, 'mod_name': 'GCC/6.4.0-2.28'}

First list contains 1 additional elements.
First extra element 1:
{'default': None, 'mod_name': 'GCC/6.4.0-2.28'}

- [{'default': None, 'mod_name': 'EasyBuild/3.8.1'},
-  {'default': None, 'mod_name': 'GCC/6.4.0-2.28'}]
? ^

+ [{'default': None, 'mod_name': 'GCC/6.4.0-2.28'}]
? ^
:
DIFF:
- [{'default': None, 'mod_name': 'EasyBuild/3.8.1'},
-  {'default': None, 'mod_name': 'GCC/6.4.0-2.28'}]? ^
+ [{'default': None, 'mod_name': 'GCC/6.4.0-2.28'}]

----------------------------------------------------------------------
Ran 595 tests in 1196.864s

FAILED (failures=6, errors=1)

Generating XML reports...
ERROR: Not all tests were successful.
Log available at /tmp/eb-7eG3Bv/eb-JcnMcd/easybuild-tests-SXc1jQ.log , XML output of tests available in test-reports directory
```

**Comment by boegel** [comment]
@surak I'm working on a cleanup of the tests to get rid of all the silly warnings that are being thrown at you, but which are actually fine.

The failing tests is another matter, it seems the tests are not as well isolated as they should be.

In particular, it looks like several tests are failing because you have EasyBuild installed as a module, I'll try to look into fixing those as well.

**Comment by surak** [comment]
I'm following the documentation. I bootstrap easybuild, which becomes a module as soon as is installed, no?

**Comment by boegel** [comment]
@surak Yes, but that's not how we usually run the tests, which is why we haven't noticed this problem ourselves...

The tests are mainly there to check the internals of the EasyBuild framework, and make sure we don't break features or re-introduce bugs that we fixed previously.

If you're just installing EasyBuild to use it (rather than develop it), there's little value in running the tests.
Which doesn't mean we shouldn't fix these problems you've been reporting, of course...

**Comment by surak** [comment]
Oh, then I will stop it; I thought it was a full sanity check on the system. Perhaps that could be clarified on the documentation?

**Comment by boegel** [comment]
excessive warnings have been dealt with in #2782, check has been added to Travis to avoid re-introducing them
