### ISSUE TITLE
EB 3.9.3 regression for --tmp-logdir

### ISSUE THREAD

**Issue by akesandgren** [easybuilders/easybuild-framework#2971]
With EB 3.9.2 this works in an empty directory:
```
eb ASE-3.15.0-intel-2017b-Python-2.7.14.eb --robot --tmp-logdir=`pwd`/tmplogs
```

But with 3.9.3 it crashes:
```
eb ASE-3.15.0-intel-2017b-Python-2.7.14.eb --robot --tmp-logdir=`pwd`/tmplogs 
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/cvmfs/ebsw.hpc2n.umu.se/amd64_ubuntu1604_common/software/Core/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/main.py", line 457, in <module>
    main()
  File "/cvmfs/ebsw.hpc2n.umu.se/amd64_ubuntu1604_common/software/Core/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/main.py", line 193, in main
    eb_go, cfg_settings = set_up_configuration(args=args, logfile=logfile, testing=testing)
  File "/cvmfs/ebsw.hpc2n.umu.se/amd64_ubuntu1604_common/software/Core/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/tools/options.py", line 1296, in set_up_configuration
    colorize=options.color, tmp_logdir=options.tmp_logdir)
  File "/cvmfs/ebsw.hpc2n.umu.se/amd64_ubuntu1604_common/software/Core/EasyBuild/3.9.3/lib/python2.7/site-packages/easybuild_framework-3.9.3-py2.7.egg/easybuild/tools/build_log.py", line 201, in init_logging
    fd, logfile = tempfile.mkstemp(suffix='.log', prefix='easybuild-', dir=tmp_logdir)
  File "/usr/lib/python2.7/tempfile.py", line 314, in mkstemp
    return _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/import/ebswbuild/home/easybuild/q/tmplogs/easybuild-sD5Vcp.log'
```

**Comment by boegel** [comment]
reproduced, I'll look into it...

**Comment by boegel** [comment]
@akesandgren This was introduced with #2937; bug squashed in #2972 (and tests added to avoid breaking it again accidentally)

**Comment by akesandgren** [comment]
Yeah, looks good. Closing
