### ISSUE TITLE
apply_regex_substitutions fails with Python 3 when called on binary file

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3030]
hit this when testing https://github.com/easybuilders/easybuild-easyconfigs/pull/8968 with `eb` running on top of Python 3:

```
ERROR: Traceback (most recent call last):
  File "/lib/python2.7/site-packages/easybuild_framework-4.0.1.dev0-py2.7.egg/easybuild/main.py", line 112, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/lib/python2.7/site-packages/easybuild_framework-4.0.1.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 3051, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/lib/python2.7/site-packages/easybuild_framework-4.0.1.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 2959, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/lib/python2.7/site-packages/easybuild_framework-4.0.1.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 2829, in run_step
    step_method(self)()
  File "/lib/python2.7/site-packages/easybuild_framework-4.0.1.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 2190, in post_install_step
    self.fix_shebang()
  File "/lib/python2.7/site-packages/easybuild_framework-4.0.1.dev0-py2.7.egg/easybuild/framework/easyblock.py", line 2173, in fix_shebang
    apply_regex_substitutions(path, [(regex, shebang)], backup=False)
  File "/lib/python2.7/site-packages/easybuild_framework-4.0.1.dev0-py2.7.egg/easybuild/tools/filetools.py", line 1097, in apply_regex_substitutions
    for line_id, line in enumerate(fileinput.input(path, inplace=1, backup=backup_ext)):
  File "/usr/lib64/python3.6/fileinput.py", line 250, in __next__
    line = self._readline()
  File "/usr/lib64/python3.6/fileinput.py", line 364, in _readline
    return self._readline()
  File "/usr/lib64/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd6 in position 24: invalid continuation byte
```

cc @smoors

**Comment by boegel** [comment]
problem is fixed in #3029, so closing this (this issue was just a reminder-to-self...)
