### ISSUE TITLE
Easybuild 4.0.1 bootstrap fails because of vsc-install

### ISSUE THREAD

**Issue by jbd** [easybuilders/easybuild-framework#3056]
Hello,

My understanding is that Easybuild has no vsc-base, vsc-install and setuptools dependencies. If I try to bootstrap easybuild on a fresh CentOS 7, it fails during stage1 because it cannot find vsc-install requirements. 

```
[... fresh installation]
# yum -y install epel-release curl
# yum install -y Lmod
```
```
$ curl -O https://raw.githubusercontent.com/easybuilders/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
$ type python && python --version
python is hashed (/bin/python)
Python 2.7.5
$ source /etc/profile.d/z00_lmod.sh
$ EASYBUILD_PREFIX=$(pwd)/eb
$ python bootstrap_eb.py $EASYBUILD_PREFIX
[[INFO]] EasyBuild bootstrap script (version 20190922.01, MD5: 039b743a44cde1549cfc0f15796d4dcd)
[[INFO]] Found Python 2.7.5 (default, Oct 30 2018, 23:45:53) ; [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

[[INFO]] Installation prefix /tmp/eb/eb
[[INFO]] Found module command '/usr/share/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
[[INFO]] No suitable setuptools installation found, proceeding with stage 0...


[[INFO]] +++ STAGE 0: installing distribute via included (patched) distribute_setup.py...

Downloading https://easybuilders.github.io/easybuild/files/distribute-0.6.49-patched1.tar.gz
Extracting in /tmp/tmpbbBkno
Now working in /tmp/tmpbbBkno/distribute-0.6.49
Installing Distribute
[[INFO]] Installed setuptools version 0.6 (/tmp/tmpSi8k8c/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/__init__.pyc)


[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] running pre-install command 'easy_install --quiet --upgrade --prefix=/tmp/tmpSi8k8c/eb_stage1 vsc-install<0.11.4'
[[ERROR]] Running 'easy_install --quiet --upgrade --prefix=/tmp/tmpSi8k8c/eb_stage1 vsc-install<0.11.4' failed: error: Could not find suitable distribution for Requirement.parse('vsc-install<0.11.4')
Traceback (most recent call last):
  File "bootstrap_eb.py", line 368, in run_easy_install
    easy_install.main(args)
  File "/tmp/tmpSi8k8c/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/command/easy_install.py", line 1973, in main
    with_ei_usage(lambda:
  File "/tmp/tmpSi8k8c/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/command/easy_install.py", line 1954, in with_ei_usage
    return f()
  File "/tmp/tmpSi8k8c/lib/python2.7/site-packages/distribute-0.6.49-py2.7.egg/setuptools/command/easy_install.py", line 1977, in <lambda>
    distclass=DistributionWithoutHelpCommands, **kw
  File "/usr/lib64/python2.7/distutils/core.py", line 169, in setup
    raise SystemExit, "error: " + str(msg)
SystemExit: error: Could not find suitable distribution for Requirement.parse('vsc-install<0.11.4')
```

FWIW, if I install python-setuptools package, to bootstrap is working fine. But since setuptools is not a requirements, I guess something is wrong here. Maybe I didn't understand something here ? Here is the ouput anyway:
```
python bootstrap_eb.py $EASYBUILD_PREFIX
[[INFO]] EasyBuild bootstrap script (version 20190922.01, MD5: 039b743a44cde1549cfc0f15796d4dcd)
[[INFO]] Found Python 2.7.5 (default, Oct 30 2018, 23:45:53) ; [GCC 4.8.5 20150623 (Red Hat 4.8.5-36)]

[[INFO]] Installation prefix /tmp/eb/eb
[[INFO]] Found module command '/usr/share/lmod/lmod/libexec/lmod' via $LMOD_CMD (Lmod), so using it.
[[INFO]] Suitable setuptools installation already found, skipping stage 0...


[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] running pre-install command 'easy_install --quiet --upgrade --prefix=/tmp/tmpD6uSKn/eb_stage1 vsc-install<0.11.4'
[[INFO]] running pre-install command 'easy_install --quiet --upgrade --prefix=/tmp/tmpD6uSKn/eb_stage1 vsc-base<2.9.0'
[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpD6uSKn/eb_stage1 easybuild'

[[INFO]] Note: a 'SyntaxError' may be reported for the easybuild/tools/py2vs3/py3.py module.
You can safely ignore this message, it will not affect the functionality of the EasyBuild installation.

  File "build/bdist.linux-x86_64/egg/easybuild/tools/py2vs3/py3.py", line 82
    class WrapperBase(object, metaclass=metaclass):
                                       ^
SyntaxError: invalid syntax

[[INFO]] running post install command 'easy_install --upgrade --prefix=/tmp/tmpD6uSKn/eb_stage1 vsc-base<2.9.0'


[[INFO]] +++ STAGE 2: installing EasyBuild in /tmp/eb/eb with EasyBuild from stage 1...

== temporary log file in case of crash /tmp/eb-XmtUlE/easybuild-imIj3M.log

WARNING: Deprecated functionality, will no longer work in v5.0: Use of 'dummy' toolchain is deprecated, use 'system' toolchain instead; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information

== processing EasyBuild easyconfig /tmp/tmpD6uSKn/EasyBuild-4.0.1.eb
== building and installing EasyBuild/4.0.1...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== patching...
== preparing...
== configuring...
== building...
== testing...
== installing...
== taking care of extensions...
== restore after iterating...
== postprocessing...
== sanity checking...
== cleaning up...
== creating module...
== permissions...
== packaging...
== COMPLETED: Installation ended successfully (took 8 sec)
== Results of the build can be found in the log file(s) /tmp/eb/eb/software/EasyBuild/4.0.1/easybuild/easybuild-EasyBuild-4.0.1-20191019.153930.log
== Build succeeded for 1 out of 1
== Temporary log file(s) /tmp/eb-XmtUlE/easybuild-imIj3M.log* have been removed.
== Temporary directory /tmp/eb-XmtUlE has been removed.
[[INFO]] EasyBuild module installed: /tmp/eb/eb/modules/all/EasyBuild/4.0.1.lua

[[INFO]] Bootstrapping EasyBuild completed!

[[INFO]] EasyBuild v4.0.1 was installed to /tmp/eb/eb, so make sure your $MODULEPATH includes /tmp/eb/eb/modules/all

[[INFO]] Run 'module load EasyBuild', and run 'eb --help' to get help on using EasyBuild.
[[INFO]] Set $EASYBUILD_MODULES_TOOL to 'Lmod' to use the same modules tool as was used now.

[[INFO]] By default, EasyBuild will install software to $HOME/.local/easybuild.
[[INFO]] To install software with EasyBuild to /tmp/eb/eb, set $EASYBUILD_INSTALLPATH accordingly.
[[INFO]] See http://easybuild.readthedocs.org/en/latest/Configuration.html for details on configuring EasyBuild.
```

**Comment by boegel** [comment]
The problem here is that the `distribute` that gets installed during stage 0 of the bootstrap (if `setuptools` is not available on the system) is too old to talk to PyPI...

While EasyBuild itself does not require `setuptools`, `vsc-install` or `vsc-base`, the bootstrap script isn't fully taking this into account yet. It still tries to use `easy_install` (which is provided by `setuptools`), among other things...

More work is needed to clean that up.

**Comment by jbd** [comment]
OK, this was confusing, but now it's clear to me. Thank you for the answer.
