### ISSUE TITLE
GC3Pie-2.5.2.eb - Error while compiling

### ISSUE THREAD

**Issue by nortex** [easybuilders/easybuild-framework#3063]
Hi, i am trying to compile GC3Pie-2.5.2.eb with the standard command:

`eb GC3Pie-2.5.2.eb -r`

EB version:  3.9.4
OS: CentOS 6.7

During the extensions installation i get the next error: 

```
== 2019-10-27 14:02:01,748 run.py:192 INFO running cmd: unzip -qq /data/sources/g/GC3Pie/extensions/setuptools-41.0.1.zip
== 2019-10-27 14:02:02,396 run.py:192 INFO running cmd: /usr/bin/python -V
== 2019-10-27 14:02:02,430 run.py:192 INFO running cmd: /usr/bin/python -c 'import sys; print(sys.executable)'
== 2019-10-27 14:02:02,484 environment.py:97 INFO Environment variable PYTHONNOUSERSITE set to 1 (previously undefined)
== 2019-10-27 14:02:02,485 run.py:192 INFO running cmd: /usr/bin/python -c 'import sys; print(sys.path)'
== 2019-10-27 14:02:02,539 run.py:192 INFO running cmd:  /usr/bin/python setup.py build
== 2019-10-27 14:02:03,189 build_log.py:163 ERROR EasyBuild crashed with an error (at ?:124 in __init__): cmd " /usr/bin/python setup.py build " exited with exit code 1 and output:
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/setuptools/__init__.py", line 18, in <module>
    import setuptools.version
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/pkg_resources/__init__.py", line 959, in <module>
    class Environment:
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/pkg_resources/__init__.py", line 963, in Environment
    self, search_path=None, platform=get_supported_platform(),
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/pkg_resources/__init__.py", line 190, in get_supported_platform
    plat = get_build_platform()
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/pkg_resources/__init__.py", line 393, in get_build_platform
    from sysconfig import get_platform
ImportError: No module named sysconfig
 (at easybuild/tools/run.py:501 in parse_cmd_output)
== 2019-10-27 14:02:03,189 easyblock.py:3053 WARNING build failed (first 300 chars): cmd " /usr/bin/python setup.py build " exited with exit code 1 and output:
Traceback (most recent call last):
  File "setup.py", line 11, in <module>
    import setuptools
  File "/data/sources/build/GC3Pie/2.5.2/dummy-dummy/setuptools/setuptools-41.0.1/setuptools/__init__.py", line 18, in <module>
```
Any ideas what is the problem?

**Comment by ocaisa** [comment]
Setuptools dropped support for Python2.6 in version 37, edit the easyconfig to use `36.8.0` (but you may run in to other problems elsewhere...)

**Comment by ocaisa** [comment]
If you do run into other problems, this will probably work (it uses older versions of all the python dependencies):
```
eb --try-software-version=2.5.3 GC3Pie-2.5.0.eb
```

**Comment by nortex** [comment]
> Setuptools dropped support for Python2.6 in version 37, edit the easyconfig to use `36.8.0` (but you may run in to other problems elsewhere...)

Now i have the next error (trying to install the 2.5.0 version to avoid checksum errors):

== installing extension docutils 0.14 (11/24)...
== FAILED: Installation ended unsuccessfully (build directory: /data/sources/build/GC3Pie/2.5.0/dummy-): build failed (first 300 chars): cmd "tar xzf /data/sources/g/GC3Pie/extensions/docutils-0.14.tar.gz" exited with exit code 2 and output:
tar: docutils-0.14/test/functional/input/data/html4css1.css: Cannot hard link to `docutils-0.14/docutils/writers/html4css1/html4css1.css': Operation not permitted
tar: docutils-0.14/test/function (took 2 min 9 sec)
== Results of the build can be found in the log file(s) /tmp/eb-knZUmS/easybuild-GC3Pie-2.5.0-20191028.132738.lLTYI.log
ERROR: Build of /data/apps/Easybuild/ebfiles_repo/GC3Pie/GC3Pie-2.5.0.eb failed (err: 'build failed (first 300 chars): cmd "tar xzf /data/sources/g/GC3Pie/extensions/docutils-0.14.tar.gz" exited with exit code 2 and output:\ntar: docutils-0.14/test/functional/input/data/html4css1.css: Cannot hard link to `docutils-0.14/docutils/writers/html4css1/html4css1.css\': Operation not permitted\ntar: docutils-0.14/test/function')

**Comment by ocaisa** [comment]
This is not related to the EasyBuild framework so I am going to transfer it over to the easyconfigs repo.
