### ISSUE TITLE
bootstrap.py gives the error: Missing checksum for easybuild-framework-4.0.1.tar.gz

### ISSUE THREAD

**Issue by npklein** [easybuilders/easybuild-framework#3079]
I am trying to install EasyBuild (in my own directory, there is already an EasyBuild installation on the cluster) using

```
wget https://raw.githubusercontent.com/easybuilders/easybuild-framework/develop/easybuild/scripts/bootstrap_eb.py
python bootstrap_eb.py $HPC_ENV_PREFIX
```

However, I get the error `Missing checksum for easybuild-framework-4.0.1.tar.gz`.

When I check in `/tmp/tmpn2t9qS/EasyBuild-4.0.1.eb` it indeed does not have a checksum for this .tar.gz file. At what point should I add the checksum?

Full log:

```
[[INFO]] EasyBuild bootstrap script (version 20190922.01, MD5: 039b743a44cde1549cfc0f15796d4dcd)
[[INFO]] Found Python 2.7.5 (default, Aug  7 2019, 00:51:29) ; [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]

[[INFO]] Installation prefix /groups/umcg-biogen/tmp01/apps
[[INFO]] Using modules tool specified by $EASYBUILD_MODULES_TOOL: Lmod
[[INFO]] Suitable setuptools installation already found, skipping stage 0...


[[INFO]] +++ STAGE 1: installing EasyBuild in temporary dir with easy_install...

[[INFO]] running pre-install command 'easy_install --quiet --upgrade --prefix=/tmp/tmpKa4iCe/eb_stage1 vsc-install<0.11.4'
[[INFO]] running pre-install command 'easy_install --quiet --upgrade --prefix=/tmp/tmpKa4iCe/eb_stage1 vsc-base<2.9.0'
[[INFO]] installing EasyBuild with 'easy_install --quiet --upgrade --prefix=/tmp/tmpKa4iCe/eb_stage1 easybuild'

[[INFO]] Note: a 'SyntaxError' may be reported for the easybuild/tools/py2vs3/py3.py module.
You can safely ignore this message, it will not affect the functionality of the EasyBuild installation.

  File "build/bdist.linux-x86_64/egg/easybuild/tools/py2vs3/py3.py", line 82
    class WrapperBase(object, metaclass=metaclass):
                                       ^
SyntaxError: invalid syntax

[[INFO]] running post install command 'easy_install --upgrade --prefix=/tmp/tmpKa4iCe/eb_stage1 vsc-base<2.9.0'


[[INFO]] +++ STAGE 2: installing EasyBuild in /groups/umcg-biogen/tmp01/apps with EasyBuild from stage 1...

== temporary log file in case of crash /tmp/eb-9ZGii6/easybuild-9IYkZs.log

WARNING: Deprecated functionality, will no longer work in v5.0: Use of 'dummy' toolchain is deprecated, use 'system' toolchain instead; see http://easybuild.readthedocs.org/en/latest/Deprecated-functionality.html for more information


== processing EasyBuild easyconfig /tmp/tmpKa4iCe/EasyBuild-4.0.1.eb
== building and installing EasyBuild/4.0.1...
== fetching files...
== creating build dir, resetting environment...
== unpacking...
== FAILED: Installation ended unsuccessfully (build directory: /tmp/tmpKa4iCe/EasyBuild/4.0.1/dummy-dummy): build failed (first 300 chars): Missing checksum for easybuild-framework-4.0.1.tar.gz (took 0 sec)
== Results of the build can be found in the log file(s) /tmp/eb-9ZGii6/easybuild-EasyBuild-4.0.1-20191112.182429.gWqCz.log
Traceback (most recent call last):
  File "bootstrap_eb.py", line 1124, in <module>
    main()
  File "bootstrap_eb.py", line 927, in main
    stage2(tmpdir, templates, install_path, distribute_egg_dir, sourcepath)
  File "bootstrap_eb.py", line 790, in stage2
    easybuild_main()
  File "/tmp/tmpKa4iCe/eb_stage1/lib/python2.7/site-packages/easybuild_framework-4.0.1-py2.7.egg/easybuild/main.py", line 434, in main
    ecs_with_res = build_and_install_software(ordered_ecs, init_session_state, exit_on_failure=exit_on_failure)
  File "/tmp/tmpKa4iCe/eb_stage1/lib/python2.7/site-packages/easybuild_framework-4.0.1-py2.7.egg/easybuild/main.py", line 147, in build_and_install_software
    raise EasyBuildError(test_msg)
easybuild.tools.build_log.EasyBuildError: "Build of /tmp/tmpKa4iCe/EasyBuild-4.0.1.eb failed (err: 'build failed (first 300 chars): Missing checksum for easybuild-framework-4.0.1.tar.gz')"
```

**Comment by boegel** [comment]
Your current configuration apparently has `--enforce-checksums` enabled, which explains the problem you're seeing.

The bootstrap script auto-generates an easyconfig file, but it doesn't include checksums (it could I guess, with a bit more work).

You can dance around this though, by temporarily disabling the checksums requirement, only for the bootstrap:

```
EASYBUILD_DISABLE_ENFORCE_CHECKSUMS=1 python bootstrap <path>
```


If you want to, you can bootstrap EasyBuild to a temporary location (for example `/tmp/$USER`), and then use that installation to pull in an easyconfig file that does have checksums, using "`eb --from-pr 9149`" (which pulls in the easyconfig from https://github.com/easybuilders/easybuild-easyconfigs/pull/9149/files).

We could enhance the bootstrap script to either also add SHA256 checksums in the generated easyconfig file, or to always set `$EASYBUILD_DISABLE_ENFORCE_CHECKSUMS` before starting the 2nd stage of the bootstrap...

**Comment by npklein** [comment]
EASYBUILD_DISABLE_ENFORCE_CHECKSUMS=1 fixed it, thank you!
