### ISSUE TITLE
gen_easyblocks_overview_rst fails if easyblock is missing docstrings

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3113]
```
Traceback (most recent call last):
  File "scripts/gen_easyblocks_docs.py", line 64, in <module>
    easyblocks_overview = gen_easyblocks_overview_rst(so.options.module, so.options.examples, COMMON_PARAMS, DOC_FUNCTIONS)
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/docs.py", line 826, in gen_easyblocks_overview_rst
    doc.extend(gen_easyblock_doc_section_rst(eb_class, path_to_examples, common_params, doc_functions, all_blocks))
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/docs.py", line 870, in gen_easyblock_doc_section_rst
    doc.extend([eb_class.__doc__.strip(), ''])
AttributeError: 'NoneType' object has no attribute 'strip'
```

We should make the doc more robust to avoid tripping over this...

**Comment by migueldiascosta** [comment]
fixed by #3144
