### ISSUE TITLE
Problems installing and using the GitHub token on Fedora 32

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-framework#3336]
I'm seeing problems with `GitHub` integration on a `Fedora 32` machine.

It appears to be related to how it's trying to store the token.

Here's a typical session:

```
 eb --install-github-token --debug
== temporary log file in case of crash /tmp/eb-apap1zes/easybuild-vwj47wc5.log
Token:
Validating token...
Token seems to be valid, installing it.
Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/adam/EasyBuild/lib/python3.8/site-packages/easybuild/main.py", line 521, in <module>
    main()
  File "/home/adam/EasyBuild/lib/python3.8/site-packages/easybuild/main.py", line 241, in main
    install_github_token(options.github_user, silent=build_option('silent'))
  File "/home/adam/EasyBuild/lib/python3.8/site-packages/easybuild/tools/github.py", line 1984, in install_github_token
    keyring.set_password(KEYRING_GITHUB_TOKEN, github_user, token)
  File "/usr/lib/python3.8/site-packages/keyring/core.py", line 62, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/usr/lib/python3.8/site-packages/keyring/backends/SecretService.py", line 85, in set_password
    collection = self.get_preferred_collection()
  File "/usr/lib/python3.8/site-packages/keyring/backends/SecretService.py", line 63, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

It appears to be because this command tries to open a graphical password prompt window, which fails:
```
May 12 23:03:50 gnome-keyring-daemon[5817]: couldn't create system prompt: Timeout was reached
May 12 23:03:50  gnome-keyring-d[5817]: couldn't create system prompt: Timeout was reached
```

and it ends up with:
```
python3[6327]: detected unhandled Python exception in '/home/adam/EasyBuild/lib/python3.8/site-packages/easybuild/main.py'
```
I have `python3-keyring-21.2.0-1.fc32.noarch` installed, which has the following backends:
```
keyring --list-backends
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: -1)
keyring.backends.fail.Keyring (priority: 0)
```

It *does* appear to work in a graphical login session, but normally I will be connecting remotely to this machine.

**Comment by boegel** [comment]
@verdurin Do you also have the [`keyrings.alt` Python package](https://pypi.org/project/keyrings.alt/) installed?

**Comment by verdurin** [comment]
@boegel No, I was hoping to avoid it.

Perhaps there's no other way.
