### ISSUE TITLE
Traceback when trying to build container image

### ISSUE THREAD

**Issue by sjpb** [easybuilders/easybuild-framework#3431]
I'm trying to follow the approach described [here](https://easybuild.readthedocs.io/en/latest/Containers.html#generating-container-recipes-containerize-c) to build a container with the Intel MPI Benchmarks and OSU Micro Benchmarks.

Both of these have a `gompi-2019.a` toolchain version, and when I tried to build a container for that `eb` told me there was one already, which is great:
```shell
(hpc-tests) [centos@eb-login-0 mpitests]$ eb -C --container-build-image gompi-2019a.eb --container-config bootstrap=yum,osversion=7 --experimental
== temporary log file in case of crash /tmp/eb-9swfo1xx/easybuild-ms7n00g2.log
== singularity tool found at /usr/local/bin/singularity
== singularity version '3.6.2' is 2.4 or higher ... OK
== sudo tool found at /usr/bin/sudo
ERROR: Container recipe at /mnt/nfs/centos/easybuild/containers/Singularity.gompi-2019a already exists, not overwriting it without --force
```

When I try to use that as a base image for a container with the IMB and OMB applications though, I get a traceback:

```shell
(hpc-tests) [centos@eb-login-0 mpitests]$ eb -C --container-build-image -D IMB-2019.3-gompi-2019a.eb OSU-Micro-Benchmarks-5.6.2-gompi-2019a.eb --container-config bootstrap=localimage,/mnt/nfs/centos/easybuild/containers/Singularity.gompi-2019a --experimental
== temporary log file in case of crash /tmp/eb-0b35jqlr/easybuild-2k43n_1p.log
== found valid index for /mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/easybuild/easyconfigs, so using it...
== singularity tool found at /usr/local/bin/singularity
== singularity version '3.6.2' is 2.4 or higher ... OK
== sudo tool found at /usr/bin/sudo
Traceback (most recent call last):
  File "/home/centos/miniconda3/envs/hpc-tests/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/centos/miniconda3/envs/hpc-tests/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/lib/python3.7/site-packages/easybuild/main.py", line 533, in <module>
    main()
  File "/mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/lib/python3.7/site-packages/easybuild/main.py", line 390, in main
    containerize(easyconfigs)
  File "/mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/lib/python3.7/site-packages/easybuild/tools/containers/common.py", line 56, in containerize
    klass(easyconfigs).generate()
  File "/mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/lib/python3.7/site-packages/easybuild/tools/containers/base.py", line 67, in generate
    recipe_path = self.generate_recipe()
  File "/mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/lib/python3.7/site-packages/easybuild/tools/containers/base.py", line 115, in generate_recipe
    data = self.resolve_template_data()
  File "/mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/lib/python3.7/site-packages/easybuild/tools/containers/singularity.py", line 254, in resolve_template_data
    template_data.update(self.resolve_template_data_config())
  File "/mnt/nfs/centos/easybuild/software/EasyBuild/4.2.2/lib/python3.7/site-packages/easybuild/tools/containers/singularity.py", line 212, in resolve_template_data_config
    key, value = item.split('=', 1)
ValueError: not enough values to unpack (expected 2, got 1)
```

I'm probably doing something wrong with how I'm referring to the base image, but I have no idea what.

**Comment by sjpb** [comment]
Ok this is a misunderstanding, I only had the recipe not an image. I'm trying to build the container directly now from that recipe, some issues but they're not this one so closing.
