### ISSUE TITLE
crash in apply_regex_substitutions in EasyBuild v4.3.1 when passing list of paths to patch

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3493]
```
ERROR: Traceback (most recent call last):
  File "/.../easybuild/main.py", line 115, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/.../easybuild/framework/easyblock.py", line 3325, in build_and_install_one
    result = app.run_all_steps(run_test_cases=run_test_cases)
  File "/.../easybuild/framework/easyblock.py", line 3228, in run_all_steps
    self.run_step(step_name, step_methods)
  File "/.../easybuild/framework/easyblock.py", line 3083, in run_step
    step_method(self)()
  File "/.../easybuild/easyblocks/g/gcc.py", line 310, in configure_step
    apply_regex_substitutions(gcc_config_headers, regex_subs)
  File "/.../easybuild/tools/filetools.py", line 1312, in apply_regex_substitutions
    with open(path, 'r') as fp:
TypeError: expected str, bytes or os.PathLike object, not list
```

I ran into this when installing `GCCcore` with a custom `--sysroot`.

Based on the easyblocks using `apply_regex_substitutions`, this is also a problem when installing TINKER with an `intel` toolchain.

**Comment by boegel** [comment]
A workaround for the GCC easyblock is available in https://github.com/easybuilders/easybuild-easyblocks/pull/2217, so if you're hitting this bug you can dance around it via `--include-easyblocks-from-pr 2217`...
