### ISSUE TITLE
limit testing of bootstrap script in CI

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#3639]
We sometimes see failing tests in CI due to what seems like hitting a rate limit in PyPI, so we should probably test the bootstrap script a bit less often, or flesh out the testing of the bootstrap script in a separate workflow?

**Comment by boegel** [comment]
Example failure when testing bootstrap script in GitHub Actions (2 failed test runs out of 50+):
```
[[ERROR]] Running 'easy_install --quiet --upgrade --prefix=/tmp/tmpd2v2bxwr/eb_stage1 easybuild>=4.0' failed: error: Could not find suitable distribution for Requirement.parse('easybuild-easyblocks==4.3.3')
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 410, in run
    self.easy_install(spec, not self.no_deps)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 697, in install_item
    self.process_distribution(spec, dist, deps)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 742, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/pkg_resources/__init__.py", line 850, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1122, in best_match
    return self.obtain(req, installer)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1134, in obtain
    return installer(requirement)
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 659, in easy_install
    raise DistutilsError(msg)
distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('easybuild-easyblocks==4.3.3')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "easybuild/scripts/bootstrap_eb.py", line 380, in run_easy_install
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/site-packages/setuptools/command/easy_install.py", line 2265, in main
    **kw
  File "/opt/hostedtoolcache/Python/3.5.10/x64/lib/python3.5/distutils/core.py", line 163, in setup
    raise SystemExit("error: " + str(msg))
SystemExit: error: Could not find suitable distribution for Requirement.parse('easybuild-easyblocks==4.3.3')
```

**Comment by ocaisa** [comment]
I am seeing this too in https://github.com/ocaisa/easybuild-framework/runs/2306415900?check_suite_focus=true , funny that is only Python 3.5?

**Comment by boegel** [comment]
Yeah, I think it mostly happens with Python 3.5.

I'll flesh out the testing of the bootstrap script in a separate workflow, and just skip testing with Python 3.5 there...

It must be an update on the PyPI side, or a problem specific to Python 3.5, it's not worth breaking the tests over that again and again...
