### ISSUE TITLE
404 error when trying to use --merge-pr

### ISSUE THREAD

**Issue by verdurin** [easybuilders/easybuild-framework#3822]
Here is an error I've seen when trying to use `--merge-pr` with EB 4.4.2:
```
eb --merge-pr 8719
== Temporary log file in case of crash /tmp/eb-dlpef_z_/easybuild-6tl_ciq9.log

easybuilders/easybuild-easyconfigs PR #8719 was submitted by boegel, you are using GitHub account 'verdurin'

PR title: {bio}[foss/2018b] FMRIprep v1.4.1 w/ Python 3.6.6


Checking eligibility of easybuilders/easybuild-easyconfigs PR #8719 for merging...
* targets develop branch: OK
* test suite passes: OK
* last test report is successful: OK
* no pending change requests: OK
* approved review: OK (by verdurin)
* milestone is set: OK (release after 4.4.2)
* mergeable state is clean: OK

Review OK, merging pull request!

Adding comment to easybuild-easyconfigs issue #8719: 'Going in, thanks @boegel!'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/eb/maint/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/main.py", line 560, in <module>
    main()
  File "/eb/maint/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/main.py", line 262, in main
    merge_pr(options.merge_pr)
  File "/eb/maint/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/github.py", line 1455, in merge_pr
    github_api_put_request(merge_url, github_user, body=body)
  File "/eb/maint/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/tools/github.py", line 306, in github_api_put_request
    status, data = url.put(**kwargs)
  File "/eb/maint/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/base/rest.py", line 145, in put
    return self.request(self.PUT, url, json.dumps(body), headers, content_type='application/json')
  File "/eb/maint/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/base/rest.py", line 174, in request
    conn = self.get_connection(method, url, body, headers)
  File "/eb/maint/software/EasyBuild/4.4.2/lib/python3.6/site-packages/easybuild/base/rest.py", line 215, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by SebastianAchilles** [comment]
Another data point: https://github.com/easybuilders/easybuild-easyconfigs/pull/13393 with ` eb --merge 13393` failed.

**Comment by SebastianAchilles** [comment]
Another data point: https://github.com/easybuilders/easybuild-easyconfigs/pull/13175 with `eb --merge-pr 13175`:

```
easybuilders/easybuild-easyconfigs PR #13175 was submitted by robert-mijakovic, you are using GitHub account 'sebastianachilles'

PR title: {chem}[GCC/10.3.0] Libint v2.6.0


Checking eligibility of easybuilders/easybuild-easyconfigs PR #13175 for merging...
* targets develop branch: OK
* test suite passes: OK
* last test report is successful: OK
* no pending change requests: OK
* approved review: OK (by SebastianAchilles)
* milestone is set: OK (next release (4.5.0?))
* mergeable state is clean: OK

Review OK, merging pull request!

Adding comment to easybuild-easyconfigs issue #13175: 'Going in, thanks @robert-mijakovic!'
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/achilles/.local/lib/python3.8/site-packages/easybuild/main.py", line 560, in <module>
    main()
  File "/home/achilles/.local/lib/python3.8/site-packages/easybuild/main.py", line 262, in main
    merge_pr(options.merge_pr)
  File "/home/achilles/.local/lib/python3.8/site-packages/easybuild/tools/github.py", line 1455, in merge_pr
    github_api_put_request(merge_url, github_user, body=body)
  File "/home/achilles/.local/lib/python3.8/site-packages/easybuild/tools/github.py", line 306, in github_api_put_request
    status, data = url.put(**kwargs)
  File "/home/achilles/.local/lib/python3.8/site-packages/easybuild/base/rest.py", line 145, in put
    return self.request(self.PUT, url, json.dumps(body), headers, content_type='application/json')
  File "/home/achilles/.local/lib/python3.8/site-packages/easybuild/base/rest.py", line 174, in request
    conn = self.get_connection(method, url, body, headers)
  File "/home/achilles/.local/lib/python3.8/site-packages/easybuild/base/rest.py", line 215, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/usr/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

**Comment by SebastianAchilles** [comment]
I just hit the `404` error when I tried to merge https://github.com/easybuilders/easybuild-easyconfigs/pull/14814 with `--merge-pr`. In this case it was related to the recent changes to the CI configurations. A `--sync-pr-with-develop` solved this issue for this PR.

**Comment by bedroge** [comment]
I just had the same problem with https://github.com/easybuilders/easybuild-easyconfigs/pull/17011:
```
== Temporary log file in case of crash /data/eb/tmp/eb-gtoxwhsl/easybuild-ku6gw88k.log

easybuilders/easybuild-easyconfigs PR #17011 was submitted by iotaka, you are using GitHub account 'bedroge'

PR title: {chem}[foss/2022a] Cantera v2.6.0 w/ Python 3.10.4


Checking eligibility of easybuilders/easybuild-easyconfigs PR #17011 for merging...
* targets develop branch: OK
* test suite passes: OK
* last test report is successful: OK
* no pending change requests: OK
* approved review: OK (by bedroge)
* milestone is set: OK (next release (4.7.2))
* mergeable state is clean: OK

Review OK, merging pull request!

Adding comment to easybuild-easyconfigs issue #17011: 'Going in, thanks @iotaka!'
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/data/apps/software/EasyBuild/4.7.1/lib/python3.10/site-packages/easybuild/main.py", line 734, in <module>
    main()
  File "/data/apps/software/EasyBuild/4.7.1/lib/python3.10/site-packages/easybuild/main.py", line 657, in main
    merge_pr(options.merge_pr)
  File "/data/apps/software/EasyBuild/4.7.1/lib/python3.10/site-packages/easybuild/tools/github.py", line 1469, in merge_pr
    github_api_put_request(merge_url, github_user, body=body)
  File "/data/apps/software/EasyBuild/4.7.1/lib/python3.10/site-packages/easybuild/tools/github.py", line 308, in github_api_put_request
    status, data = url.put(**kwargs)
  File "/data/apps/software/EasyBuild/4.7.1/lib/python3.10/site-packages/easybuild/base/rest.py", line 147, in put
    return self.request(self.PUT, url, json.dumps(body), headers, content_type='application/json')
  File "/data/apps/software/EasyBuild/4.7.1/lib/python3.10/site-packages/easybuild/base/rest.py", line 176, in request
    conn = self.get_connection(method, url, body, headers)
  File "/data/apps/software/EasyBuild/4.7.1/lib/python3.10/site-packages/easybuild/base/rest.py", line 217, in get_connection
    connection = self.opener.open(request)
  File "/usr/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```
