### ISSUE TITLE
exception with eb --install-github-token

### ISSUE THREAD

**Issue by scicomp-moffitt** [easybuilders/easybuild-framework#3831]
I am having this error: on RHEL 8.4 / EB 4.2.2

```
[scicomp@li1314-234 mcc_easyconfigs]$ eb --install-github-token --debug
== Temporary log file in case of crash /tmp/eb-8lo_zv04/easybuild-9iq_pov_.log
Token:
Validating token...
Token seems to be valid, installing it.
Traceback (most recent call last):
  File "/home/scicomp/.local/lib/python3.6/site-packages/keyring/backends/libsecret.py", line 89, in set_password
    self.schema, attributes, self.collection, label, password, None
GLib.Error: g-io-error-quark: Cannot autolaunch D-Bus without X11 $DISPLAY (0)
```

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/scicomp/.local/lib/python3.6/site-packages/easybuild/main.py", line 560, in <module>
    main()
  File "/home/scicomp/.local/lib/python3.6/site-packages/easybuild/main.py", line 253, in main
    install_github_token(options.github_user, silent=build_option('silent'))
  File "/home/scicomp/.local/lib/python3.6/site-packages/easybuild/tools/github.py", line 2203, in install_github_token
    keyring.set_password(KEYRING_GITHUB_TOKEN, github_user, token)
  File "/home/scicomp/.local/lib/python3.6/site-packages/keyring/core.py", line 60, in set_password
    get_keyring().set_password(service_name, username, password)
  File "/home/scicomp/.local/lib/python3.6/site-packages/keyring/backends/chainer.py", line 58, in set_password
    return keyring.set_password(service, username, password)
  File "/home/scicomp/.local/lib/python3.6/site-packages/keyring/backends/libsecret.py", line 97, in set_password
    raise KeyringLocked("Failed to unlock the collection!") from error
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

**Comment by scicomp-moffitt** [comment]
removed keyring, keyrings.alt packages, rebooted and reinstalled packages (keyring==20.0). This worked

**Comment by boegel** [comment]
@scicomp-moffitt Thanks for sharing how you fixed this.

It doesn't look like we can do much about this, looks like a problem with `keyring` itself, so this issue can be closed?

**Comment by branfosj** [comment]
See https://github.com/jaraco/keyring/pull/521#issuecomment-908472497

Based on the merge data of that PR, I think we want keyring <= 23.1.0.
