### ISSUE TITLE
Singularity: missing 'USER' inside container leads to crashing of imkl installation

### ISSUE THREAD

**Issue by sassy-crick** [easybuilders/easybuild-framework#3896]
I am installing software via a Singularity container, similarly to what EESSI does. Thus I do:

```
singularity exec --bind ${BINDDIR} --fusemount "container:${OVERLAY_BASEDIR}/fuse-overlayfs -o lowerdir=${OVERLAY_LOWERDIR} -o upperdir=${OVERLAY_UPPERDIR} -o workdir=${OVERLAY_WORKDIR} ${OVERLAY_MOUNTPOINT}" ${CONTAINER} ${SOFTWARE}
```
With `CONTAINER` being the full path for the container and `SOFTWARE` being just the script which sets up the environment and installs the software:
```
#!/usr/bin/env bash
# setting up the environment:
shopt -s expand_aliases
export EASYBUILD_BUILDPATH="/dev/shm"
export EASYBUILD_TMPDIR="/dev/shm/easybuild"
export EASYBUILD_PARALLEL="36"
export MODULEPATH="/app/modules/all"
alias eb="eb --robot --download-timeout=100"
# building stuff
eb --fetch foss-2020a.eb  
eb foss-2020a.eb  
```
That works well but for the newer foss-toolchains, which require `imkl` and that crashes with:
```
== processing EasyBuild easyconfig /app/software/EasyBuild/4.5.0/easybuild/easyconfigs/i/imkl/imkl-2021.4.0.eb
0:00:09  6 out of 155 easyconfigs done: flex/2.6.4 (OK), Bison/3.5.3 (OK), Bison/3.7.6 (OK), Bison/3.7.1 (OK), M4/1.4.19 (OK), M4/1.4.18 (OK)
ERROR: Traceback (most recent call last):
  File "/app/software/EasyBuild/4.5.0/lib/python3.8/site-packages/easybuild/main.py", line 128, in build_and_install_software
    (ec_res['success'], app_log, err) = build_and_install_one(ec, init_env)
  File "/app/software/EasyBuild/4.5.0/lib/python3.8/site-packages/easybuild/framework/easyblock.py", line 3865, in build_and_install_one
    app = app_class(ecdict['ec'])
  File "/app/software/EasyBuild/4.5.0/lib/python3.8/site-packages/easybuild/easyblocks/i/imkl.py", line 71, in __init__
    super(EB_imkl, self).__init__(*args, **kwargs)
  File "/app/software/EasyBuild/4.5.0/lib/python3.8/site-packages/easybuild/easyblocks/generic/intelbase.py", line 110, in __init__
    self.home_subdir_local = os.path.join(common_tmp_dir, os.getenv('USER'), 'easybuild_intel')
  File "/usr/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib/python3.8/genericpath.py", line 152, in _check_arg_types
    raise TypeError(f'{funcname}() argument must be str, bytes, or '
TypeError: join() argument must be str, bytes, or os.PathLike object, not 'NoneType'
```
The reason being is that `USER` is not defined inside a container. 
In my case, I can simply add:
```
# we need this to get some software installed as
# USER is not defined inside the container
# whereas HOME is:
USER=$(whoami)
export USER
```
inside the script above and that will make it work. 
However, I am wondering if there is a better way to do that within the framework for example?
Thanks!

**Comment by akesandgren** [comment]
That's a bit odd. USER is defined in my build container.

**Comment by boegel** [comment]
Not having `$USER` defined is a very strange environment.

I think the best we can do in EasyBuild is to produce a big fat warning when that happens, probably for both `$USER` and `$HOME`, since that's bound to cause problems for various software installations.

**Comment by sassy-crick** [comment]
Not an EasyBuild issue but if somebody comes across that on here:
```
[sassy@deepblue new]$ /usr/local/singularity-3.5.3/bin/singularity shell zlib-1.2.11-ubuntu-focal-lmod.sif
Singularity> echo $USER
sassy
Singularity> exit
exit
[sassy@deepblue new]$ /usr/local/singularity-3.7.1/bin/singularity shell zlib-1.2.11-ubuntu-focal-lmod.sif
Singularity> echo $USER

Singularity> 
```
So the same container contains the `USER` or not, depending on the version of Singularity used. 
I patched that by this:
```
%environment
# setting up the installation environment:
USER=$(whoami)
```
within the Singularity Definition file. 
I am happy to close that as the issue is not EasyBuild related. 
Thanks!
