### ISSUE TITLE
Misdectection of EnvironnementModules version when use a non-released module version

### ISSUE THREAD

**Issue by tristanlt** [easybuilders/easybuild-framework#4126]
Hi,
Using unreleased version of `cea-hpc/modules` leads to a misdetection of `module` version by EasyBuild.

When `module --version` for unreleased version
```
Modules Release 4.7.1+13-g15cdc75 (2021-04-25)
```
For instance, released version tell
```
Modules Release 4.8.0 (2021-07-14)
```
EasyBuild Configuration
```
[config]
module-syntax=Tcl
modules-tool=EnvironmentModules
```

EasyBuild failed with "invalid version number" error.
```
(venv_easybuild_u22) admin@ran:~$ eb 
== Temporary log file in case of crash /tmp/eb-hdr88n8f/easybuild-xvpquc0b.log
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/linux/apps/tools/venv_easybuild_u22/lib/python3.10/site-packages/easybuild/main.py", line 597, in <module>
    main()
  File "/opt/linux/apps/tools/venv_easybuild_u22/lib/python3.10/site-packages/easybuild/main.py", line 249, in main
    modtool = modules_tool(testing=testing)
  File "/opt/linux/apps/tools/venv_easybuild_u22/lib/python3.10/site-packages/easybuild/tools/modules.py", line 1681, in modules_tool
    return modules_tool_class(mod_paths=mod_paths, testing=testing)
  File "/opt/linux/apps/tools/venv_easybuild_u22/lib/python3.10/site-packages/easybuild/tools/modules.py", line 207, in __init__
    self.set_and_check_version()
  File "/opt/linux/apps/tools/venv_easybuild_u22/lib/python3.10/site-packages/easybuild/tools/modules.py", line 263, in set_and_check_version
    if StrictVersion(self.version) < StrictVersion(self.REQ_VERSION):
  File "/usr/lib/python3.10/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python3.10/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '4.7.1+13-g15cdc75'
```

Software versions
- Ubuntu 22.04
- Python 3.10.6
- easybuild==4.5.2
- easybuild-easyblocks==4.5.2
- easybuild-easyconfigs==4.5.2
- easybuild-framework==4.5.2

Best regards,
Tristan

**Comment by boegel** [comment]
@tristanlt Indeed, that regular expression doesn't take into account that there may be extra "junk" after the `4.7.1` version...
