### ISSUE TITLE
Accidentally using `('CUDA', version, SYSTEM)`  instead of `('CUDA', version, '', SYSTEM)` leads to cryptic errors

### ISSUE THREAD

**Issue by Micket** [easybuilders/easybuild-framework#4181]
A result of the combination of the use of the SYSTEM dictionary and and dependencies that provide templates (like CUDA), leads to very cryptic stacktrace. We should handle this error more gracefully.

Example

```python
easyblock = 'PythonBundle'

name = 'test'
version = '1'
homepage = 'test'
description = 'test'
toolchain = {'name': 'foss', 'version': '2021b'}

dependencies = [
    ('CUDA', '11.4.1', SYSTEM),      # mistake
    #('CUDA', '11.4.1', '', SYSTEM),  # correct
]

moduleclass = 'lib'
```

which will produce 

```text
$ eb test-1-foss-2021b-CUDA-11.4.1.eb -Dr 
== Temporary log file in case of crash /dev/shm/eb-u5kjewsj/easybuild-iebk87vj.log
== found valid index for /apps/Common/software/EasyBuild/4.7.0/easybuild/easyconfigs, so using it...
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/main.py", line 727, in <module>
    main()
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/main.py", line 717, in main
    hooks, do_build)
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/main.py", line 393, in process_eb_args
    raise err
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/main.py", line 382, in process_eb_args
    easyconfigs, generated_ecs = parse_easyconfigs(paths, validate=validate)
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/tools.py", line 407, in parse_easyconfigs
    easyconfigs.extend(process_easyconfig(ec_file, **kwargs))
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 2071, in process_easyconfig
    ec = EasyConfig(spec, build_specs=build_specs, validate=validate, hidden=hidden)
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 516, in __init__
    self.parse()
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 773, in parse
    self._finalize_dependencies()
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 1660, in _finalize_dependencies
    tc = robot_find_subtoolchain_for_dep(dep, self.modules_tool)
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 2300, in robot_find_subtoolchain_for_dep
    mod_name = ActiveMNS().det_full_module_name(newdep, require_result=False)
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 2633, in det_full_module_name
    require_result=require_result)
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/framework/easyconfig/easyconfig.py", line 2605, in _det_module_name_with
    mod_name = mns_method(ec)
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/tools/module_naming_scheme/easybuild_mns.py", line 51, in det_full_module_name
    return os.path.join(ec['name'], det_full_ec_version(ec))
  File "/apps/Common/software/EasyBuild/4.7.0/lib/python3.6/site-packages/easybuild/tools/module_naming_scheme/utilities.py", line 65, in det_full_ec_version
    ecver = ''.join([x for x in [ec.get('versionprefix', ''), ecver, ec.get('versionsuffix', '')] if x])
TypeError: sequence item 1: expected str instance, dict found
```

**Comment by aryatalathi** [comment]
Is this issues solved? I would like to work on it if it is yet to be solved. Thank you.
