### ISSUE TITLE
Error when creating existing directory

### ISSUE THREAD

**Issue by Flamefire** [easybuilders/easybuild-framework#4326]
I recently got the following error:
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/EasyBuildDev/easybuild-framework/easybuild/main.py", line 753, in <module>
    init_session_state, eb_go, cfg_settings = prepare_main()
  File "/EasyBuildDev/easybuild-framework/easybuild/main.py", line 747, in prepare_main
    eb_go, cfg_settings = set_up_configuration(args=args, logfile=logfile, testing=testing)
  File "/EasyBuildDev/easybuild-framework/easybuild/tools/options.py", line 1553, in set_up_configuration
    colorize=options.color, tmp_logdir=options.tmp_logdir)
  File "/EasyBuildDev/easybuild-framework/easybuild/tools/build_log.py", line 213, in init_logging
    raise EasyBuildError("Failed to create temporary log directory %s: %s", tmp_logdir, err)
easybuild.tools.build_log.EasyBuildError: "Failed to create temporary log directory /tmp/easybuild-tmplog: [Errno 17] File exists: '/tmp/easybuild-tmplog'"
```

This is similar to what I fixed in #4300 and also applies to various other places where we do `if not exists(p): mkdirs(p)` which in Python 3 can be simplified to `os.mkdirs(p, exists_ok=True)`

--> Refactor all current uses of `os.mkdirs` for EB 5.0

**Comment by boegel** [comment]
@Flamefire Is this still a TODO?

**Comment by Flamefire** [comment]
I think so yes. The initial problem was that we call `os.makedirs` if the path does not exist. But we have a race condition: If the path gets created between the check and the actual invocation of the bottom-most function (e.g. syscall or so) we get the FileExistsError.

One such occurrence is https://github.com/easybuilders/easybuild-framework/blob/717a2769267b10ff5c7b74d84ef502fbb18ef5fa/easybuild/tools/filetools.py#L2799-L2800

So not only can we simplify this we'll also avoid the race
