### ISSUE TITLE
`ModuleNotFoundError` for `distutils` when running with Python 3.12 without setuptools

### ISSUE THREAD

**Issue by boegel** [easybuilders/easybuild-framework#4493]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/kehoste/work/easybuild-framework/easybuild/main.py", line 50, in <module>
    from easybuild.tools.build_log import EasyBuildError, print_error, print_msg, print_warning, stop_logging
  File "/Users/kehoste/work/easybuild-framework/easybuild/tools/__init__.py", line 40, in <module>
    import distutils.version
ModuleNotFoundError: No module named 'distutils'
```

**Comment by boegel** [comment]
This is fixed in `5.0.x` branch, so will be fixed for EasyBuild 5.0.0 (cfr. #3963)
